from __future__ import annotations

from pathlib import Path

import pytest

from dotagent.backup import (
    MANAGED_FILES,
    backup_existing,
    list_backups,
    restore_all,
    restore_one,
)
from dotagent.paths import Paths
from dotagent.scaffold import scaffold_agent_dir


def _setup(tmp_path: Path) -> Paths:
    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    return paths


def test_backup_skips_when_no_existing_files(tmp_path: Path):
    paths = _setup(tmp_path)
    results = backup_existing(paths)
    assert results == []


def test_backup_copies_existing_claude_md(tmp_path: Path):
    paths = _setup(tmp_path)
    original = "# my hand-written CLAUDE.md\n\n## Rules\n\nNever ship on Friday.\n"
    (tmp_path / "CLAUDE.md").write_text(original)

    results = backup_existing(paths)
    ok = [r for r in results if r.ok]
    assert len(ok) == 1
    assert ok[0].name == "claude"
    backup = paths.imported / "CLAUDE.md.original"
    assert backup.exists()
    assert backup.read_text() == original


def test_backup_skips_files_already_dotagent_managed(tmp_path: Path):
    paths = _setup(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- generated by dotagent — DO NOT EDIT -->\n\n# auto\n"
    )
    results = backup_existing(paths)
    skipped = [r for r in results if not r.ok]
    assert any(r.name == "claude" and "dotagent-managed" in r.skipped_reason for r in skipped)
    assert not (paths.imported / "CLAUDE.md.original").exists()


def test_backup_idempotent_does_not_overwrite_first_backup(tmp_path: Path):
    paths = _setup(tmp_path)
    original = "# v1 (real)\n"
    (tmp_path / "CLAUDE.md").write_text(original)
    backup_existing(paths)
    # later, dotagent re-renders, then user runs sync again with new content
    (tmp_path / "CLAUDE.md").write_text("# v2 (already overwritten)\n")
    results = backup_existing(paths)
    skipped = [r for r in results if r.skipped_reason == "backup already exists"]
    assert any(r.name == "claude" for r in skipped)
    # first backup still intact
    assert (paths.imported / "CLAUDE.md.original").read_text() == original


def test_backup_handles_multiple_managed_files(tmp_path: Path):
    paths = _setup(tmp_path)
    (tmp_path / "CLAUDE.md").write_text("# claude\n")
    (tmp_path / ".cursorrules").write_text("# cursor\n")
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "copilot-instructions.md").write_text("# copilot\n")

    results = backup_existing(paths)
    ok_names = {r.name for r in results if r.ok}
    assert ok_names == {"claude", "cursor", "copilot"}
    assert (paths.imported / "CLAUDE.md.original").exists()
    assert (paths.imported / ".cursorrules.original").exists()
    assert (paths.imported / "copilot-instructions.md.original").exists()


def test_restore_one_writes_back_to_source(tmp_path: Path):
    paths = _setup(tmp_path)
    original = "# original\n\nimportant content.\n"
    (tmp_path / "CLAUDE.md").write_text(original)
    backup_existing(paths)
    # simulate dotagent overwriting
    (tmp_path / "CLAUDE.md").write_text("# generated by dotagent\n")

    target = restore_one(paths, "claude")
    assert target == tmp_path / "CLAUDE.md"
    assert target.read_text() == original


def test_restore_one_errors_when_no_backup(tmp_path: Path):
    paths = _setup(tmp_path)
    with pytest.raises(FileNotFoundError):
        restore_one(paths, "claude")


def test_restore_all_only_restores_what_exists(tmp_path: Path):
    paths = _setup(tmp_path)
    (tmp_path / "CLAUDE.md").write_text("# claude original\n")
    backup_existing(paths)
    (tmp_path / "CLAUDE.md").write_text("# dotagent regen\n")

    restored = restore_all(paths)
    assert len(restored) == 1
    assert restored[0].name == "CLAUDE.md"


def test_list_backups_returns_sorted_paths(tmp_path: Path):
    paths = _setup(tmp_path)
    (tmp_path / "CLAUDE.md").write_text("# a\n")
    (tmp_path / ".cursorrules").write_text("# b\n")
    backup_existing(paths)
    backups = list_backups(paths)
    names = [b.name for b in backups]
    assert "CLAUDE.md.original" in names
    assert ".cursorrules.original" in names


def test_init_then_sync_backs_up_only_once(tmp_path: Path, monkeypatch):
    """End-to-end: existing file → init backs it up → second sync doesn't double-back-up."""
    from dotagent.commands.init_cmd import init
    from click.testing import CliRunner

    (tmp_path / "CLAUDE.md").write_text("# pre-existing\n\n## Rules\n\nKeep this.\n")
    monkeypatch.chdir(tmp_path)
    # initialize git so dotagent can find repo root
    import subprocess
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=tmp_path, check=True)

    runner = CliRunner()
    result = runner.invoke(init, ["--no-llm", "--no-hooks"])
    assert result.exit_code == 0, result.output
    backup = tmp_path / ".agent" / ".imported" / "CLAUDE.md.original"
    assert backup.exists()
    assert "pre-existing" in backup.read_text()
