"""Tests for the dotgraph probe + doctor JSON + sync emit-docs pre-step.

dotgraph is an external tool. We don't depend on it being installed in the
test runner. Instead each test shims a fake `dotgraph` binary on PATH that
behaves the way the test needs (--version returns text, status returns JSON,
emit-docs writes a docs/dependency-map.md file, etc.).

Coverage matrix:
- probe: installed × db_present × dirty matrix
- probe: dotgraph crashes → error captured, stale=True
- probe: bad JSON → error captured
- doctor JSON: gains `dotgraph` envelope; existing `diagnoses` list still there
- doctor text: emits the one-line dotgraph summary
- sync: emit-docs runs when db present
- sync: emit-docs skipped when db absent
- sync: emit-docs skipped when --skip-dotgraph
- sync: emit-docs failure is logged but doesn't break sync
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

import pytest
from click.testing import CliRunner

from dotagent.commands.doctor_cmd import doctor
from dotagent.commands.sync_cmd import sync
from dotagent.config import merge_defaults
from dotagent.dotgraph_probe import DotgraphInfo, emit_docs, probe
from dotagent.paths import Paths
from dotagent.scaffold import scaffold_agent_dir
from dotagent.util import dump_yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _install_dotgraph_shim(
    tmp_path: Path,
    *,
    version_out: str = "dotgraph, version 0.1.8",
    status_json: dict | None = None,
    status_exit: int = 0,
    emit_docs_exit: int = 0,
    emit_docs_writes: list[str] | None = None,
    crash_on: str | None = None,
    monkeypatch,
) -> Path:
    """Create a shim `dotgraph` binary on PATH that emulates dotgraph's
    surface. Returns the bin directory.

    `version_out` — what `dotgraph --version` prints to stdout.
    `status_json` — dict to emit on `dotgraph status --json`. If None,
        the default {"files":42,"dirty_files":0,"nodes":7361,
        "edges":12000,"unresolved":3} is used.
    `status_exit` — exit code for `status`.
    `emit_docs_exit` — exit code for `emit-docs`.
    `emit_docs_writes` — list of relative paths to write under the cwd's
        docs/ directory when emit-docs runs (simulates real behavior).
        Defaults to ["dependency-map.md"].
    `crash_on` — if set, the shim raises an error on that subcommand
        (`status`, `emit-docs`, or `--version`).
    """
    bin_dir = tmp_path / "fake-bin"
    bin_dir.mkdir(exist_ok=True)

    status_dict = status_json if status_json is not None else {
        "files": 42, "dirty_files": 0, "nodes": 7361,
        "edges": 12000, "unresolved": 3, "db": ".dotgraph/graph.db",
    }
    writes = emit_docs_writes if emit_docs_writes is not None else ["dependency-map.md"]

    script = f"""#!/usr/bin/env python3
import json
import os
import sys

argv = sys.argv[1:]
if {crash_on!r}:
    if (argv and argv[0] == {crash_on!r}) or ({crash_on!r} == "--version" and argv == ["--version"]):
        print("boom: simulated dotgraph crash", file=sys.stderr)
        sys.exit(2)

if argv == ["--version"]:
    print({version_out!r})
    sys.exit(0)
if argv[:1] == ["status"]:
    if "--json" in argv:
        print(json.dumps({status_dict!r}))
    else:
        for k, v in {status_dict!r}.items():
            print(f"{{k:14s}} {{v}}")
    sys.exit({status_exit})
if argv[:1] == ["emit-docs"]:
    # v0.5.4-compatible shim: honors --out-dir, --skip-empty, --json.
    # Defaults match real dotgraph 0.1.10+ behavior.
    out_dir = "docs"
    if "--out-dir" in argv:
        out_dir = argv[argv.index("--out-dir") + 1]
    skip_empty = "--skip-empty" in argv
    as_json = "--json" in argv

    # Optional shim knob — env var ALL_EMPTY=1 makes every target "empty"
    # so --skip-empty drops them all (used to test the skipped list path).
    empty_targets = set()
    if os.environ.get("ALL_EMPTY") == "1":
        empty_targets = {{"kafka-topics", "redis-key-registry"}}

    docs_dir = os.path.join(os.getcwd(), out_dir)
    os.makedirs(docs_dir, exist_ok=True)
    written = []
    skipped = []
    for rel in {writes!r}:
        target_name = rel.replace(".md", "").replace(".generated", "")
        if skip_empty and target_name in empty_targets:
            skipped.append(target_name)
            continue
        full = os.path.join(docs_dir, rel)
        with open(full, "w") as fh:
            fh.write("<!-- generated by fake dotgraph -->\\nshim content\\n")
        written.append({{"target": target_name, "path": full,
                        "bytes": os.path.getsize(full)}})
        if not as_json:
            print(f"wrote {{full}}")
    if as_json:
        from datetime import datetime, timezone
        print(json.dumps({{
            "written": written,
            "skipped": skipped,
            "rendered_at": datetime.now(timezone.utc).isoformat(),
        }}))
    sys.exit({emit_docs_exit})
print(f"unknown subcommand: {{argv}}", file=sys.stderr)
sys.exit(64)
"""
    bin_path = bin_dir / "dotgraph"
    bin_path.write_text(script)
    bin_path.chmod(bin_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Prepend to PATH so this shim wins.
    existing = os.environ.get("PATH", "")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{existing}")
    return bin_dir


def _make_dotgraph_db(repo: Path) -> Path:
    (repo / ".dotgraph").mkdir(parents=True, exist_ok=True)
    db = repo / ".dotgraph" / "graph.db"
    db.write_bytes(b"")
    return db


def _make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    paths = Paths(repo=repo)
    scaffold_agent_dir(paths)
    dump_yaml(paths.config, merge_defaults({"project": {"name": "T"}}))
    # Mark the .agent/ schema as current — structure check would otherwise
    # fail with `.agent/.version` missing → doctor would exit 1.
    from dotagent.canonical_structure import CURRENT_SCHEMA_VERSION
    (paths.agent / ".version").write_text(CURRENT_SCHEMA_VERSION + "\n")
    return repo


# ---------------------------------------------------------------------------
# probe()
# ---------------------------------------------------------------------------

def test_probe_dotgraph_not_on_path(tmp_path: Path, monkeypatch):
    """Without dotgraph on PATH → installed=False, every other field null."""
    # Clear PATH so dotgraph definitely isn't found.
    monkeypatch.setenv("PATH", "/nonexistent")
    info = probe(tmp_path)
    assert info.installed is False
    assert info.version is None
    assert info.db_present is False
    assert info.dirty_files is None
    assert info.last_indexed is None
    assert info.stale is False
    assert info.error is None


def test_probe_installed_no_db(tmp_path: Path, monkeypatch):
    """dotgraph on PATH, but no `.dotgraph/graph.db` → installed=True,
    db_present=False, other status fields null. No subprocess call for
    status (saves time on cold projects)."""
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.version == "0.1.8"
    assert info.db_present is False
    assert info.dirty_files is None


def test_probe_installed_db_present_clean(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.version == "0.1.8"
    assert info.db_present is True
    assert info.dirty_files == 0
    assert info.nodes == 7361
    assert info.edges == 12000
    assert info.unresolved == 3
    assert info.files == 42
    assert info.stale is False
    assert info.error is None
    # last_indexed not in dotgraph status JSON → null
    assert info.last_indexed is None


def test_probe_dirty_files_marks_stale(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 7, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.dirty_files == 7
    assert info.stale is True


# ---------------------------------------------------------------------------
# v0.5.4 — stale alarm + reasons + threshold
# ---------------------------------------------------------------------------

def test_probe_emits_threshold_in_output(tmp_path: Path, monkeypatch):
    """`stale_threshold_hours` always present in DotgraphInfo.to_dict()."""
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    d = info.to_dict()
    assert "stale_threshold_hours" in d
    assert d["stale_threshold_hours"] == 168   # default 7d


def test_probe_threshold_override_via_kwarg(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path, stale_threshold_hours=24)
    assert info.stale_threshold_hours == 24


def test_probe_stale_reasons_includes_dirty_files(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 7, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.stale is True
    assert "dirty_files" in info.stale_reasons


def test_probe_stale_reasons_includes_last_indexed_too_old(tmp_path: Path, monkeypatch):
    from datetime import datetime, timedelta, timezone
    eight_days_ago = (datetime.now(timezone.utc) - timedelta(days=8)).isoformat()
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 0, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
            "last_indexed": eight_days_ago,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)   # default threshold 168h = 7d
    assert info.stale is True
    assert "last_indexed_too_old" in info.stale_reasons
    # `dirty_files` is NOT a reason here
    assert "dirty_files" not in info.stale_reasons


def test_probe_fresh_when_last_indexed_within_threshold(tmp_path: Path, monkeypatch):
    from datetime import datetime, timedelta, timezone
    six_days_ago = (datetime.now(timezone.utc) - timedelta(days=6)).isoformat()
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 0, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
            "last_indexed": six_days_ago,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.stale is False
    assert info.stale_reasons == []


def test_probe_threshold_kwarg_makes_younger_index_stale(tmp_path: Path, monkeypatch):
    from datetime import datetime, timedelta, timezone
    two_days_ago = (datetime.now(timezone.utc) - timedelta(days=2)).isoformat()
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 0, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
            "last_indexed": two_days_ago,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path, stale_threshold_hours=24)   # tighter than default
    assert info.stale is True
    assert "last_indexed_too_old" in info.stale_reasons


def test_probe_dirty_AND_old_lists_both_reasons(tmp_path: Path, monkeypatch):
    from datetime import datetime, timedelta, timezone
    eight_days_ago = (datetime.now(timezone.utc) - timedelta(days=8)).isoformat()
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 5, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
            "last_indexed": eight_days_ago,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.stale is True
    assert "dirty_files" in info.stale_reasons
    assert "last_indexed_too_old" in info.stale_reasons


def test_doctor_json_emits_stale_reasons_and_threshold(
    tmp_path: Path, monkeypatch
):
    """v0.5.4 — `doctor --format json` exposes stale_reasons + threshold
    so orchestrators can branch programmatically."""
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 100, "dirty_files": 9, "nodes": 5000,
            "edges": 8000, "unresolved": 1,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    dg = payload["dotgraph"]
    assert dg["stale"] is True
    assert "stale_reasons" in dg
    assert "dirty_files" in dg["stale_reasons"]
    assert dg["stale_threshold_hours"] == 168


def test_doctor_respects_config_threshold(tmp_path: Path, monkeypatch):
    """`dotagent.dotgraph.stale_threshold_hours: N` in config.yaml overrides
    the default."""
    import yaml as _yaml
    from datetime import datetime, timedelta, timezone

    repo = _make_repo(tmp_path)
    cfg_path = repo / ".agent" / "config.yaml"
    cfg = _yaml.safe_load(cfg_path.read_text())
    cfg.setdefault("dotagent", {}).setdefault("dotgraph", {})[
        "stale_threshold_hours"] = 12
    cfg_path.write_text(_yaml.safe_dump(cfg))

    two_days_ago = (datetime.now(timezone.utc) - timedelta(days=2)).isoformat()
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 0, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
            "last_indexed": two_days_ago,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    payload = json.loads(result.output)
    dg = payload["dotgraph"]
    assert dg["stale_threshold_hours"] == 12
    assert dg["stale"] is True
    assert "last_indexed_too_old" in dg["stale_reasons"]


def test_doctor_text_emits_hint_when_stale(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 100, "dirty_files": 9, "nodes": 5000,
            "edges": 8000, "unresolved": 1,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    # The hint mentions the action + dirty count
    assert "hint: run `dotgraph index" in result.output
    assert "9 dirty files" in result.output


def test_doctor_text_no_hint_when_fresh(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "hint:" not in result.output


def test_probe_status_crash_captures_error(tmp_path: Path, monkeypatch):
    """dotgraph status crash → installed=True, db_present=True, error set,
    stale=True (conservative default)."""
    _install_dotgraph_shim(
        tmp_path, status_exit=1, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.db_present is True
    assert info.error is not None
    assert "exit=1" in info.error
    assert info.stale is True


def test_probe_bad_json_captures_error(tmp_path: Path, monkeypatch):
    """status returns junk on stdout → JSON parse error captured."""
    bin_dir = tmp_path / "fake-bin"
    bin_dir.mkdir()
    bin_path = bin_dir / "dotgraph"
    bin_path.write_text(
        "#!/usr/bin/env python3\n"
        "import sys\n"
        "if sys.argv[1:] == ['--version']:\n"
        "    print('dotgraph, version 0.1.8')\n"
        "    sys.exit(0)\n"
        "if sys.argv[1:2] == ['status']:\n"
        "    print('not json {{')\n"
        "    sys.exit(0)\n"
        "sys.exit(64)\n"
    )
    bin_path.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}")

    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.error is not None
    assert "parse error" in info.error
    assert info.stale is True


# ---------------------------------------------------------------------------
# emit_docs()
# ---------------------------------------------------------------------------

def test_emit_docs_not_installed(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("PATH", "/nonexistent")
    ok, msg, _payload = emit_docs(tmp_path)
    assert ok is False
    assert "not on PATH" in msg


def test_emit_docs_success_writes_files(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "db-impact-map.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    ok, msg, _payload = emit_docs(tmp_path)
    assert ok is True
    assert "ok" in msg
    assert (tmp_path / "docs" / "dependency-map.md").exists()
    assert (tmp_path / "docs" / "db-impact-map.md").exists()


def test_emit_docs_non_zero_exit_returns_false(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path, emit_docs_exit=3, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    ok, msg, _payload = emit_docs(tmp_path)
    assert ok is False
    assert "exit=3" in msg


# ---------------------------------------------------------------------------
# v0.5.4 — emit_docs JSON + --skip-empty
# ---------------------------------------------------------------------------

def test_emit_docs_returns_parsed_json_payload(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "db-impact-map.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    ok, msg, payload = emit_docs(tmp_path)
    assert ok is True
    assert isinstance(payload, dict)
    assert "written" in payload
    assert len(payload["written"]) == 2
    # Each written entry carries target + path + bytes
    for entry in payload["written"]:
        assert "target" in entry and "path" in entry and "bytes" in entry


def test_emit_docs_skip_empty_surfaces_skipped_list(
    tmp_path: Path, monkeypatch
):
    """When --skip-empty drops targets, payload.skipped lists them and
    the human-readable message mentions both counts."""
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=[
            "dependency-map.md", "db-impact-map.md",
            "kafka-topics.md", "redis-key-registry.md", "endpoints.md",
        ],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    monkeypatch.setenv("ALL_EMPTY", "1")
    ok, msg, payload = emit_docs(tmp_path, skip_empty=True)
    assert ok is True
    assert payload["skipped"] == ["kafka-topics", "redis-key-registry"] or \
           set(payload["skipped"]) == {"kafka-topics", "redis-key-registry"}
    assert "skipped" in msg
    assert "kafka-topics" in msg
    assert "redis-key-registry" in msg


def test_emit_docs_skip_empty_false_emits_all(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "kafka-topics.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    monkeypatch.setenv("ALL_EMPTY", "1")  # would mark kafka empty
    ok, msg, payload = emit_docs(tmp_path, skip_empty=False)
    assert ok is True
    # With skip_empty=False the shim doesn't drop any target
    assert payload.get("skipped") in ([], None)


def test_emit_docs_out_dir_lands_under_codegraph(tmp_path: Path, monkeypatch):
    """--out-dir is passed through correctly."""
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    target_dir = tmp_path / "docs" / "codegraph"
    ok, msg, payload = emit_docs(tmp_path, out_dir=target_dir)
    assert ok is True
    assert (target_dir / "dependency-map.md").exists()


# ---------------------------------------------------------------------------
# v0.5.4 — ensure_gitignored
# ---------------------------------------------------------------------------

def test_gitignore_created_when_missing(tmp_path: Path):
    from dotagent.dotgraph_probe import ensure_gitignored
    msg = ensure_gitignored(tmp_path)
    assert "created" in msg
    text = (tmp_path / ".gitignore").read_text()
    assert ".dotgraph/" in text


def test_gitignore_appended_when_present_without_entry(tmp_path: Path):
    from dotagent.dotgraph_probe import ensure_gitignored
    gi = tmp_path / ".gitignore"
    gi.write_text("node_modules/\n*.pyc\n")
    msg = ensure_gitignored(tmp_path)
    assert "added" in msg
    text = gi.read_text()
    assert "node_modules/" in text  # preserved
    assert "*.pyc" in text          # preserved
    assert ".dotgraph/" in text     # appended


def test_gitignore_noop_when_entry_already_present(tmp_path: Path):
    from dotagent.dotgraph_probe import ensure_gitignored
    gi = tmp_path / ".gitignore"
    gi.write_text("node_modules/\n.dotgraph/\n")
    before = gi.read_text()
    msg = ensure_gitignored(tmp_path)
    assert msg == ""
    assert gi.read_text() == before


def test_gitignore_tolerates_variant_entries(tmp_path: Path):
    """Variants like `.dotgraph` (no slash) or `/.dotgraph/` should not
    cause a duplicate append."""
    from dotagent.dotgraph_probe import ensure_gitignored
    for content in (".dotgraph\n", "/.dotgraph/\n", ".dotgraph # tracked elsewhere\n"):
        gi = tmp_path / ".gitignore"
        gi.write_text(content)
        msg = ensure_gitignored(tmp_path)
        assert msg == "", f"variant '{content.strip()}' should not append again"


def test_gitignore_handles_missing_trailing_newline(tmp_path: Path):
    from dotagent.dotgraph_probe import ensure_gitignored
    gi = tmp_path / ".gitignore"
    gi.write_text("node_modules/")   # no trailing newline
    ensure_gitignored(tmp_path)
    text = gi.read_text()
    assert "\n" in text
    assert "node_modules/" in text
    assert ".dotgraph/" in text


# ---------------------------------------------------------------------------
# doctor --format json gains `dotgraph` field
# ---------------------------------------------------------------------------

def test_doctor_json_envelope_includes_dotgraph(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)

    # Envelope shape
    assert "diagnoses" in payload
    assert "dotgraph" in payload
    assert isinstance(payload["diagnoses"], list)
    assert isinstance(payload["dotgraph"], dict)

    # Required fields per spec
    dg = payload["dotgraph"]
    for k in ("installed", "version", "db_present", "db_path",
              "dirty_files", "last_indexed", "stale"):
        assert k in dg, f"doctor json missing dotgraph.{k}"
    assert dg["installed"] is True
    assert dg["version"] == "0.1.8"
    assert dg["db_present"] is True
    assert dg["dirty_files"] == 0
    assert dg["stale"] is False


def test_doctor_json_when_dotgraph_not_installed(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    monkeypatch.setenv("PATH", "/nonexistent")
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    assert result.exit_code == 0
    payload = json.loads(result.output)
    dg = payload["dotgraph"]
    assert dg["installed"] is False
    assert dg["version"] is None
    assert dg["dirty_files"] is None
    assert dg["last_indexed"] is None
    assert dg["stale"] is False


def test_doctor_text_emits_dotgraph_line_when_clean(
    tmp_path: Path, monkeypatch
):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "dotgraph" in result.output
    assert "0.1.8" in result.output
    assert "7361 nodes" in result.output
    assert "clean" in result.output


def test_doctor_text_says_not_installed(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    monkeypatch.setenv("PATH", "/nonexistent")
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "dotgraph" in result.output
    assert "not installed" in result.output


def test_doctor_text_shows_dirty_count_when_stale(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 100, "dirty_files": 9, "nodes": 5000,
            "edges": 8000, "unresolved": 1,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "9 dirty file(s)" in result.output


# ---------------------------------------------------------------------------
# sync emit-docs pre-step
# ---------------------------------------------------------------------------

def test_sync_runs_emit_docs_when_db_present(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "endpoints.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    assert "dotgraph emit-docs ok" in result.output
    assert (repo / "docs" / "dependency-map.md").exists()
    assert (repo / "docs" / "endpoints.md").exists()


def test_sync_pre_seeds_gitignore_with_dotgraph_when_db_present(
    tmp_path: Path, monkeypatch
):
    """v0.5.4 — sync's emit-docs pre-step also pre-seeds .gitignore so
    a fresh dotgraph install doesn't commit .dotgraph/graph.db."""
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    # Pre-existing .gitignore without the entry
    (repo / ".gitignore").write_text("node_modules/\n")
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    assert "added .dotgraph/ to .gitignore" in result.output
    gi = (repo / ".gitignore").read_text()
    assert "node_modules/" in gi
    assert ".dotgraph/" in gi


def test_sync_respects_skip_empty_config_knob(tmp_path: Path, monkeypatch):
    """v0.5.4 — `dotagent.dotgraph.emit_docs.skip_empty: false` in
    config.yaml forces emit-docs to write all 5 files."""
    import yaml as _yaml
    repo = _make_repo(tmp_path)
    cfg_path = repo / ".agent" / "config.yaml"
    cfg = _yaml.safe_load(cfg_path.read_text())
    cfg.setdefault("dotagent", {}).setdefault("dotgraph", {})[
        "emit_docs"] = {"skip_empty": False}
    cfg_path.write_text(_yaml.safe_dump(cfg))

    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "kafka-topics.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.setenv("ALL_EMPTY", "1")  # would skip kafka by default
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    # With skip_empty=false override, NOTHING gets dropped
    assert "skipped" not in result.output
    assert (repo / "docs" / "kafka-topics.md").exists()


def test_sync_skips_emit_docs_when_db_absent(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    # No db
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0
    assert "dotgraph emit-docs" not in result.output
    assert not (repo / "docs" / "dependency-map.md").exists()


def test_sync_skip_dotgraph_flag_suppresses_emit_docs(
    tmp_path: Path, monkeypatch
):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, ["--skip-dotgraph"])
    assert result.exit_code == 0
    assert "dotgraph emit-docs" not in result.output
    # Critically: the docs/ dir from emit-docs did NOT get written
    assert not (repo / "docs" / "dependency-map.md").exists()


def test_sync_proceeds_when_emit_docs_fails(tmp_path: Path, monkeypatch):
    """emit-docs failure logs a warning but doesn't break sync — adapters
    still render against whatever's on disk."""
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path, emit_docs_exit=5, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    assert "exit=5" in result.output
    # Adapters still wrote
    assert (repo / "CLAUDE.md").exists()
