"""Tests for structure_checker.py."""

from __future__ import annotations

from pathlib import Path

from dotagent.canonical_structure import (
    CURRENT_SCHEMA_VERSION,
    TIER_PROJECT_ROOT,
    TIER_SERVICE_REPO,
    TIER_SINGLE_REPO,
)
from dotagent.structure_checker import (
    SEVERITY_FAIL,
    SEVERITY_WARN,
    check,
)


def _scaffold_clean_single_repo(repo: Path) -> None:
    """Write a minimal single-repo layout that satisfies the schema."""
    agent = repo / ".agent"
    agent.mkdir()
    (agent / ".version").write_text(CURRENT_SCHEMA_VERSION + "\n")
    (agent / "config.yaml").write_text("name: demo\n")
    (agent / "architecture.md").write_text("# Architecture\n")
    (agent / "rules.md").write_text("# Rules\n")
    for sub in ("working", "episodic", "semantic", "personal"):
        (agent / "memory" / sub).mkdir(parents=True)


def test_clean_single_repo_has_no_fails(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    assert result.ok
    assert not result.needs_migration
    assert not [d for d in result.deviations if d.severity == SEVERITY_FAIL]


def test_missing_required_file_flagged_fail(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    (tmp_path / ".agent" / "architecture.md").unlink()

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    assert not result.ok
    fails = [d for d in result.deviations if d.severity == SEVERITY_FAIL]
    assert any(d.path == ".agent/architecture.md" for d in fails)


def test_missing_required_dir_flagged_fail(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    # remove a required memory subdir
    (tmp_path / ".agent" / "memory" / "working").rmdir()

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    fails = [d for d in result.deviations if d.severity == SEVERITY_FAIL]
    assert any(d.path == ".agent/memory/working" for d in fails)


def test_file_at_expected_dir_path_flagged(tmp_path: Path):
    # If a file exists where a directory should be, it's a structural error.
    _scaffold_clean_single_repo(tmp_path)
    (tmp_path / ".agent" / "memory" / "working").rmdir()
    (tmp_path / ".agent" / "memory" / "working").write_text("oops, a file\n")

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    fails = [d for d in result.deviations if d.severity == SEVERITY_FAIL]
    assert any(
        d.path == ".agent/memory/working" and "expected a directory" in d.reason
        for d in fails
    )


def test_missing_version_file_returns_needs_migration(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    (tmp_path / ".agent" / ".version").unlink()

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    # Missing .version → fails as a required file
    fails = [d for d in result.deviations if d.severity == SEVERITY_FAIL]
    assert any(d.path == ".agent/.version" for d in fails)
    # actual_version is None
    assert result.actual_version is None


def test_version_drift_emits_warning(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    (tmp_path / ".agent" / ".version").write_text("0.3.0\n")

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    assert result.needs_migration is True
    warns = [d for d in result.deviations if d.severity == SEVERITY_WARN]
    assert any(d.path == ".agent/.version" for d in warns)


def test_generated_file_without_banner_warns(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    # CLAUDE.md is generated; without a banner it should warn.
    (tmp_path / "CLAUDE.md").write_text("# A hand-edited file masquerading as generated\n")

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    warns = [d for d in result.deviations if d.severity == SEVERITY_WARN]
    assert any(d.path == "CLAUDE.md" for d in warns)


def test_generated_file_with_banner_passes(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- GENERATED by dotagent — do not edit -->\n# Project context\n"
    )

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    warns_on_claude = [
        d for d in result.deviations
        if d.path == "CLAUDE.md" and d.severity == SEVERITY_WARN
    ]
    assert not warns_on_claude


def test_check_result_to_dict_has_stable_shape(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    payload = result.to_dict()
    assert set(payload.keys()) == {
        "tier", "schema_version", "actual_version", "ok",
        "needs_migration", "deviations",
    }
    assert payload["tier"] == TIER_SINGLE_REPO
    assert payload["schema_version"] == CURRENT_SCHEMA_VERSION


def test_deviations_sorted_fails_before_warns(tmp_path: Path):
    _scaffold_clean_single_repo(tmp_path)
    # Inject one fail and one warn
    (tmp_path / ".agent" / "architecture.md").unlink()                      # fail
    (tmp_path / "CLAUDE.md").write_text("# no banner\n")                    # warn

    result = check(tmp_path, tier=TIER_SINGLE_REPO)
    severities = [d.severity for d in result.deviations]
    fail_idxs = [i for i, s in enumerate(severities) if s == SEVERITY_FAIL]
    warn_idxs = [i for i, s in enumerate(severities) if s == SEVERITY_WARN]
    if fail_idxs and warn_idxs:
        assert max(fail_idxs) < min(warn_idxs)


def test_check_auto_detects_tier_for_project_root(tmp_path: Path):
    # Project-root signal: presence of `.agent/git.yaml`.
    agent = tmp_path / ".agent"
    agent.mkdir()
    (agent / ".version").write_text(CURRENT_SCHEMA_VERSION + "\n")
    (agent / "config.yaml").write_text("name: demo\n")
    (agent / "architecture.md").write_text("# arch\n")
    (agent / "rules.md").write_text("# rules\n")
    (agent / "project_brief.md").write_text("# brief\n")
    (agent / "git.yaml").write_text("meta: {}\n")
    for sub in ("working", "episodic", "semantic", "personal"):
        (agent / "memory" / sub).mkdir(parents=True)

    result = check(tmp_path)  # no explicit tier
    assert result.tier == TIER_PROJECT_ROOT


def test_check_auto_detects_tier_for_service_repo(tmp_path: Path):
    agent = tmp_path / ".agent"
    agent.mkdir()
    (agent / ".version").write_text(CURRENT_SCHEMA_VERSION + "\n")
    (agent / "config.yaml").write_text("parent: ../..\nname: demo\n")
    (agent / "architecture.md").write_text("# arch\n")
    (agent / "rules.md").write_text("# rules\n")
    for sub in ("working", "episodic", "semantic", "personal"):
        (agent / "memory" / sub).mkdir(parents=True)

    result = check(tmp_path)
    assert result.tier == TIER_SERVICE_REPO
