"""Tests for the dotgraph probe + doctor JSON + sync emit-docs pre-step.

dotgraph is an external tool. We don't depend on it being installed in the
test runner. Instead each test shims a fake `dotgraph` binary on PATH that
behaves the way the test needs (--version returns text, status returns JSON,
emit-docs writes a docs/dependency-map.md file, etc.).

Coverage matrix:
- probe: installed × db_present × dirty matrix
- probe: dotgraph crashes → error captured, stale=True
- probe: bad JSON → error captured
- doctor JSON: gains `dotgraph` envelope; existing `diagnoses` list still there
- doctor text: emits the one-line dotgraph summary
- sync: emit-docs runs when db present
- sync: emit-docs skipped when db absent
- sync: emit-docs skipped when --skip-dotgraph
- sync: emit-docs failure is logged but doesn't break sync
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

import pytest
from click.testing import CliRunner

from dotagent.commands.doctor_cmd import doctor
from dotagent.commands.sync_cmd import sync
from dotagent.config import merge_defaults
from dotagent.dotgraph_probe import DotgraphInfo, emit_docs, probe
from dotagent.paths import Paths
from dotagent.scaffold import scaffold_agent_dir
from dotagent.util import dump_yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _install_dotgraph_shim(
    tmp_path: Path,
    *,
    version_out: str = "dotgraph, version 0.1.8",
    status_json: dict | None = None,
    status_exit: int = 0,
    emit_docs_exit: int = 0,
    emit_docs_writes: list[str] | None = None,
    crash_on: str | None = None,
    monkeypatch,
) -> Path:
    """Create a shim `dotgraph` binary on PATH that emulates dotgraph's
    surface. Returns the bin directory.

    `version_out` — what `dotgraph --version` prints to stdout.
    `status_json` — dict to emit on `dotgraph status --json`. If None,
        the default {"files":42,"dirty_files":0,"nodes":7361,
        "edges":12000,"unresolved":3} is used.
    `status_exit` — exit code for `status`.
    `emit_docs_exit` — exit code for `emit-docs`.
    `emit_docs_writes` — list of relative paths to write under the cwd's
        docs/ directory when emit-docs runs (simulates real behavior).
        Defaults to ["dependency-map.md"].
    `crash_on` — if set, the shim raises an error on that subcommand
        (`status`, `emit-docs`, or `--version`).
    """
    bin_dir = tmp_path / "fake-bin"
    bin_dir.mkdir(exist_ok=True)

    status_dict = status_json if status_json is not None else {
        "files": 42, "dirty_files": 0, "nodes": 7361,
        "edges": 12000, "unresolved": 3, "db": ".dotgraph/graph.db",
    }
    writes = emit_docs_writes if emit_docs_writes is not None else ["dependency-map.md"]

    script = f"""#!/usr/bin/env python3
import json
import os
import sys

argv = sys.argv[1:]
if {crash_on!r}:
    if (argv and argv[0] == {crash_on!r}) or ({crash_on!r} == "--version" and argv == ["--version"]):
        print("boom: simulated dotgraph crash", file=sys.stderr)
        sys.exit(2)

if argv == ["--version"]:
    print({version_out!r})
    sys.exit(0)
if argv[:1] == ["status"]:
    if "--json" in argv:
        print(json.dumps({status_dict!r}))
    else:
        for k, v in {status_dict!r}.items():
            print(f"{{k:14s}} {{v}}")
    sys.exit({status_exit})
if argv[:1] == ["emit-docs"]:
    docs_dir = os.path.join(os.getcwd(), "docs")
    os.makedirs(docs_dir, exist_ok=True)
    for rel in {writes!r}:
        full = os.path.join(docs_dir, rel)
        with open(full, "w") as fh:
            fh.write("<!-- generated by fake dotgraph -->\\nshim content\\n")
        print(f"wrote {{full}}")
    sys.exit({emit_docs_exit})
print(f"unknown subcommand: {{argv}}", file=sys.stderr)
sys.exit(64)
"""
    bin_path = bin_dir / "dotgraph"
    bin_path.write_text(script)
    bin_path.chmod(bin_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Prepend to PATH so this shim wins.
    existing = os.environ.get("PATH", "")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{existing}")
    return bin_dir


def _make_dotgraph_db(repo: Path) -> Path:
    (repo / ".dotgraph").mkdir(parents=True, exist_ok=True)
    db = repo / ".dotgraph" / "graph.db"
    db.write_bytes(b"")
    return db


def _make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    paths = Paths(repo=repo)
    scaffold_agent_dir(paths)
    dump_yaml(paths.config, merge_defaults({"project": {"name": "T"}}))
    # Mark the .agent/ schema as current — structure check would otherwise
    # fail with `.agent/.version` missing → doctor would exit 1.
    from dotagent.canonical_structure import CURRENT_SCHEMA_VERSION
    (paths.agent / ".version").write_text(CURRENT_SCHEMA_VERSION + "\n")
    return repo


# ---------------------------------------------------------------------------
# probe()
# ---------------------------------------------------------------------------

def test_probe_dotgraph_not_on_path(tmp_path: Path, monkeypatch):
    """Without dotgraph on PATH → installed=False, every other field null."""
    # Clear PATH so dotgraph definitely isn't found.
    monkeypatch.setenv("PATH", "/nonexistent")
    info = probe(tmp_path)
    assert info.installed is False
    assert info.version is None
    assert info.db_present is False
    assert info.dirty_files is None
    assert info.last_indexed is None
    assert info.stale is False
    assert info.error is None


def test_probe_installed_no_db(tmp_path: Path, monkeypatch):
    """dotgraph on PATH, but no `.dotgraph/graph.db` → installed=True,
    db_present=False, other status fields null. No subprocess call for
    status (saves time on cold projects)."""
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.version == "0.1.8"
    assert info.db_present is False
    assert info.dirty_files is None


def test_probe_installed_db_present_clean(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.version == "0.1.8"
    assert info.db_present is True
    assert info.dirty_files == 0
    assert info.nodes == 7361
    assert info.edges == 12000
    assert info.unresolved == 3
    assert info.files == 42
    assert info.stale is False
    assert info.error is None
    # last_indexed not in dotgraph status JSON → null
    assert info.last_indexed is None


def test_probe_dirty_files_marks_stale(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 42, "dirty_files": 7, "nodes": 7361,
            "edges": 12000, "unresolved": 3,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.dirty_files == 7
    assert info.stale is True


def test_probe_status_crash_captures_error(tmp_path: Path, monkeypatch):
    """dotgraph status crash → installed=True, db_present=True, error set,
    stale=True (conservative default)."""
    _install_dotgraph_shim(
        tmp_path, status_exit=1, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.installed is True
    assert info.db_present is True
    assert info.error is not None
    assert "exit=1" in info.error
    assert info.stale is True


def test_probe_bad_json_captures_error(tmp_path: Path, monkeypatch):
    """status returns junk on stdout → JSON parse error captured."""
    bin_dir = tmp_path / "fake-bin"
    bin_dir.mkdir()
    bin_path = bin_dir / "dotgraph"
    bin_path.write_text(
        "#!/usr/bin/env python3\n"
        "import sys\n"
        "if sys.argv[1:] == ['--version']:\n"
        "    print('dotgraph, version 0.1.8')\n"
        "    sys.exit(0)\n"
        "if sys.argv[1:2] == ['status']:\n"
        "    print('not json {{')\n"
        "    sys.exit(0)\n"
        "sys.exit(64)\n"
    )
    bin_path.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}")

    _make_dotgraph_db(tmp_path)
    info = probe(tmp_path)
    assert info.error is not None
    assert "parse error" in info.error
    assert info.stale is True


# ---------------------------------------------------------------------------
# emit_docs()
# ---------------------------------------------------------------------------

def test_emit_docs_not_installed(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("PATH", "/nonexistent")
    ok, msg = emit_docs(tmp_path)
    assert ok is False
    assert "not on PATH" in msg


def test_emit_docs_success_writes_files(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "db-impact-map.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    ok, msg = emit_docs(tmp_path)
    assert ok is True
    assert "ok" in msg
    assert (tmp_path / "docs" / "dependency-map.md").exists()
    assert (tmp_path / "docs" / "db-impact-map.md").exists()


def test_emit_docs_non_zero_exit_returns_false(tmp_path: Path, monkeypatch):
    _install_dotgraph_shim(
        tmp_path, emit_docs_exit=3, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(tmp_path)
    ok, msg = emit_docs(tmp_path)
    assert ok is False
    assert "exit=3" in msg


# ---------------------------------------------------------------------------
# doctor --format json gains `dotgraph` field
# ---------------------------------------------------------------------------

def test_doctor_json_envelope_includes_dotgraph(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)

    # Envelope shape
    assert "diagnoses" in payload
    assert "dotgraph" in payload
    assert isinstance(payload["diagnoses"], list)
    assert isinstance(payload["dotgraph"], dict)

    # Required fields per spec
    dg = payload["dotgraph"]
    for k in ("installed", "version", "db_present", "db_path",
              "dirty_files", "last_indexed", "stale"):
        assert k in dg, f"doctor json missing dotgraph.{k}"
    assert dg["installed"] is True
    assert dg["version"] == "0.1.8"
    assert dg["db_present"] is True
    assert dg["dirty_files"] == 0
    assert dg["stale"] is False


def test_doctor_json_when_dotgraph_not_installed(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    monkeypatch.setenv("PATH", "/nonexistent")
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, ["--format", "json"])
    assert result.exit_code == 0
    payload = json.loads(result.output)
    dg = payload["dotgraph"]
    assert dg["installed"] is False
    assert dg["version"] is None
    assert dg["dirty_files"] is None
    assert dg["last_indexed"] is None
    assert dg["stale"] is False


def test_doctor_text_emits_dotgraph_line_when_clean(
    tmp_path: Path, monkeypatch
):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "dotgraph" in result.output
    assert "0.1.8" in result.output
    assert "7361 nodes" in result.output
    assert "clean" in result.output


def test_doctor_text_says_not_installed(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    monkeypatch.setenv("PATH", "/nonexistent")
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "dotgraph" in result.output
    assert "not installed" in result.output


def test_doctor_text_shows_dirty_count_when_stale(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        status_json={
            "files": 100, "dirty_files": 9, "nodes": 5000,
            "edges": 8000, "unresolved": 1,
        },
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(doctor, [])
    assert result.exit_code == 0
    assert "9 dirty file(s)" in result.output


# ---------------------------------------------------------------------------
# sync emit-docs pre-step
# ---------------------------------------------------------------------------

def test_sync_runs_emit_docs_when_db_present(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path,
        emit_docs_writes=["dependency-map.md", "endpoints.md"],
        monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    assert "dotgraph emit-docs ok" in result.output
    assert (repo / "docs" / "dependency-map.md").exists()
    assert (repo / "docs" / "endpoints.md").exists()


def test_sync_skips_emit_docs_when_db_absent(tmp_path: Path, monkeypatch):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    # No db
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0
    assert "dotgraph emit-docs" not in result.output
    assert not (repo / "docs" / "dependency-map.md").exists()


def test_sync_skip_dotgraph_flag_suppresses_emit_docs(
    tmp_path: Path, monkeypatch
):
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(tmp_path, monkeypatch=monkeypatch)
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, ["--skip-dotgraph"])
    assert result.exit_code == 0
    assert "dotgraph emit-docs" not in result.output
    # Critically: the docs/ dir from emit-docs did NOT get written
    assert not (repo / "docs" / "dependency-map.md").exists()


def test_sync_proceeds_when_emit_docs_fails(tmp_path: Path, monkeypatch):
    """emit-docs failure logs a warning but doesn't break sync — adapters
    still render against whatever's on disk."""
    repo = _make_repo(tmp_path)
    _install_dotgraph_shim(
        tmp_path, emit_docs_exit=5, monkeypatch=monkeypatch,
    )
    _make_dotgraph_db(repo)
    monkeypatch.chdir(repo)

    result = CliRunner().invoke(sync, [])
    assert result.exit_code == 0, result.output
    assert "exit=5" in result.output
    # Adapters still wrote
    assert (repo / "CLAUDE.md").exists()
