"""Tests for git.yaml parsing + branch-rule verification."""

from __future__ import annotations

from pathlib import Path

import pytest

from dotagent.git_layout import (
    BranchRule,
    GitLayout,
    MAIN_BRANCH_POLICY_LOCKED,
    STRATEGY_DEDICATED_REPO,
    load,
    parse,
    render_dashboard,
    verify_paths_against_rule,
)


_SAMPLE = {
    "meta": {
        "strategy": "dedicated_repo",
        "remote": "git@github.com:org/meta.git",
        "branch": "dotagent/meta",
        "main_branch_policy": "locked",
    },
    "repos": [
        {"id": "backend", "path": "./backend", "remote": "git@github.com:org/backend.git",
         "default_branch": "main", "role": "api"},
        {"id": "portal", "path": "./portal", "remote": "git@github.com:org/portal.git",
         "default_branch": "main", "role": "frontend"},
    ],
    "branch_rules": [
        {
            "remote": "git@github.com:org/meta.git",
            "branches": {
                "main": {
                    "allowed_paths": [],
                    "forbidden_paths": ["**/*"],
                    "description": "Reserved.",
                },
                "dotagent/meta": {
                    "allowed_paths": [".agent/", "docs/", "*.md"],
                    "forbidden_paths": ["**/*.py", "**/*.ts"],
                    "description": "Meta only.",
                },
            },
        },
    ],
}


def test_parse_full_layout():
    layout = parse(_SAMPLE)
    assert layout.meta.strategy == "dedicated_repo"
    assert layout.meta.branch == "dotagent/meta"
    assert layout.meta.main_branch_policy == "locked"
    assert len(layout.repos) == 2
    assert layout.repos[0].id == "backend"
    assert layout.repos[1].role == "frontend"
    assert len(layout.branch_rules) == 1
    rr = layout.branch_rules[0]
    assert rr.remote == "git@github.com:org/meta.git"
    assert len(rr.branches) == 2


def test_parse_skips_repos_without_id_or_path():
    data = dict(_SAMPLE)
    data["repos"] = [
        {"id": "good", "path": "./good"},
        {"id": "", "path": "./bad"},      # no id
        {"id": "alsobad"},                 # no path
    ]
    layout = parse(data)
    assert len(layout.repos) == 1
    assert layout.repos[0].id == "good"


def test_load_missing_file_returns_none(tmp_path: Path):
    assert load(tmp_path / "git.yaml") is None


def test_load_malformed_yaml_raises(tmp_path: Path):
    (tmp_path / "git.yaml").write_text(": not valid yaml :\n -\n  bad")
    with pytest.raises(ValueError):
        load(tmp_path / "git.yaml")


def test_meta_branch_main_with_locked_policy_rejected():
    bad = {
        "meta": {
            "strategy": "dedicated_repo",
            "branch": "main",
            "main_branch_policy": "locked",
        }
    }
    with pytest.raises(ValueError, match="meta branch"):
        parse(bad)


def test_rules_for_finds_match():
    layout = parse(_SAMPLE)
    rule = layout.rules_for("git@github.com:org/meta.git", "dotagent/meta")
    assert rule is not None
    assert rule.branch == "dotagent/meta"


def test_rules_for_returns_none_on_miss():
    layout = parse(_SAMPLE)
    assert layout.rules_for("not-a-remote", "x") is None


def test_verify_passes_on_clean_meta_files():
    rule = BranchRule(
        branch="dotagent/meta",
        allowed_paths=[".agent/", "docs/", "*.md"],
        forbidden_paths=["**/*.py"],
    )
    ok, offenders = verify_paths_against_rule(
        [".agent/architecture.md", "docs/bug-registry.md", "README.md"], rule,
    )
    assert ok
    assert offenders == []


def test_verify_rejects_python_file_in_meta_branch():
    rule = BranchRule(
        branch="dotagent/meta",
        allowed_paths=[".agent/", "docs/"],
        forbidden_paths=["**/*.py"],
    )
    ok, offenders = verify_paths_against_rule(
        [".agent/x.md", "backend/auth.py"], rule,
    )
    assert not ok
    assert "backend/auth.py" in offenders


def test_verify_fully_locked_branch_rejects_everything():
    rule = BranchRule(
        branch="main",
        allowed_paths=[],
        forbidden_paths=["**/*"],
    )
    ok, offenders = verify_paths_against_rule(
        ["README.md", "src/x.py", ".agent/config.yaml"], rule,
    )
    assert not ok
    assert len(offenders) == 3


def test_dashboard_render_includes_meta_and_repos():
    layout = parse(_SAMPLE)
    text = render_dashboard(layout)
    assert "GENERATED by dotagent" in text
    assert "dotagent/meta" in text
    assert "backend" in text
    assert "portal" in text
    assert "Branch reservations" in text


def test_to_dict_roundtrip():
    layout = parse(_SAMPLE)
    data = layout.to_dict()
    assert data["meta"]["branch"] == "dotagent/meta"
    assert len(data["repos"]) == 2
    assert len(data["branch_rules"]) == 1
