from __future__ import annotations

from pathlib import Path

from dotagent.ingest import ingest_existing
from dotagent.memory import WorkingMemory
from dotagent.paths import Paths
from dotagent.scaffold import scaffold_agent_dir


def test_working_memory_records_events_and_dedupes_files(tmp_path: Path):
    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    wm = WorkingMemory(paths, "alice")
    wm.record_event(kind="edit", tool="claude_code", summary="touched a", files=["a.py"], branch="main", session="s1")
    wm.record_event(kind="edit", tool="cursor", summary="touched b", files=["b.py"], branch="main")
    wm.record_event(kind="edit", tool="claude_code", summary="touched a again", files=["a.py"])

    state = wm.load_current()
    assert state.actor == "alice"
    assert state.session == "s1"
    assert state.branch == "main"
    # most recent first, deduped, with last-touched at the head
    assert state.recent_files[0] == "a.py"
    assert "b.py" in state.recent_files
    assert len(state.recent_events) == 3
    # each event records its tool
    tools = {ev.tool for ev in state.recent_events}
    assert tools == {"claude_code", "cursor"}


def test_working_memory_set_task(tmp_path: Path):
    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    wm = WorkingMemory(paths, "alice")
    wm.record_event(kind="edit", tool="claude_code", files=["a.py"])
    wm.set_task("ship bug-101 fix")
    assert wm.load_current().task == "ship bug-101 fix"


def test_ingest_routes_existing_claude_md_into_buckets(tmp_path: Path):
    (tmp_path / "CLAUDE.md").write_text(
        "# Project context for Claude Code\n\n"
        "## Coding style\n\nUse 4-space indents.\n\n"
        "## Rules\n\nNever commit secrets.\n\n"
        "## Architecture\n\nMicroservices with shared Postgres.\n\n"
        "## Random other section\n\nLeftover content.\n"
    )
    out = ingest_existing(tmp_path)
    assert "Use 4-space indents" in out["style"]
    assert "Never commit secrets" in out["rules"]
    assert "Microservices" in out["architecture"]
    # leftover section preserved under "Legacy notes"
    assert "Legacy notes" in out["architecture"]
    assert "Leftover content" in out["architecture"]


def test_ingest_strips_dotagent_header(tmp_path: Path):
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- generated by dotagent — DO NOT EDIT -->\n\n"
        "# Project context for Claude Code — `demo`\n\n"
        "## Rules\n\nReal content.\n"
    )
    out = ingest_existing(tmp_path)
    assert "Real content" in out.get("rules", "")
    assert "generated by dotagent" not in out.get("rules", "")


def test_ingest_returns_empty_when_no_configs(tmp_path: Path):
    assert ingest_existing(tmp_path) == {}
