"""Tier-1 cross-repo contracts rollup: `Project Root/contracts.md`.

Walks the `repos[]` manifest in `plan.yaml`, builds a per-repo
ContractsIndex for each, and renders a single aggregated dashboard.

Lower-case filename `contracts.md` is intentional — matches the
chat-locked convention (Tier 1 = root-level lowercase, Tier 2 = repo-level
CAPS).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from ..paths import Paths
from .contracts_index import ContractsIndex, build_index
from .model import Project, load_project


@dataclass
class RepoSummary:
    """One row in the cross-repo rollup.

    `note` carries a human-readable message that may be informational
    ("no cycles tracked at this tier") or a real error ("path missing").
    `is_error` distinguishes them so renderers can style accordingly.
    `error` is kept as an alias of `note` when `is_error` is True, for
    backward compatibility with callers that read `error` directly.
    """
    id: str
    path: str
    role: str
    open: int
    frozen: int
    last_touched: str
    last_actor: str
    contracts_index_path: str
    note: str = ""
    is_error: bool = False

    @property
    def error(self) -> str:
        """Backward-compat alias: only the actual-error subset of note."""
        return self.note if self.is_error else ""

    def to_dict(self) -> dict:
        return {
            "id": self.id, "path": self.path, "role": self.role,
            "open": self.open, "frozen": self.frozen,
            "last_touched": self.last_touched, "last_actor": self.last_actor,
            "contracts_index_path": self.contracts_index_path,
            "note": self.note,
            "is_error": self.is_error,
            "error": self.error,   # backward compat: only set when is_error
        }


@dataclass
class Rollup:
    """Materialized cross-repo state."""
    project_name: str
    generated_at: str
    repos: list[RepoSummary] = field(default_factory=list)

    @property
    def total_open(self) -> int:
        return sum(r.open for r in self.repos)

    @property
    def total_frozen(self) -> int:
        return sum(r.frozen for r in self.repos)

    def to_dict(self) -> dict:
        return {
            "project_name": self.project_name,
            "generated_at": self.generated_at,
            "total_open": self.total_open,
            "total_frozen": self.total_frozen,
            "repos": [r.to_dict() for r in self.repos],
        }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_rollup(paths: Paths) -> Rollup:
    """Walk `repos[]` from plan.yaml; aggregate per-repo contracts state."""
    project = load_project(paths)
    if project is None:
        return Rollup(project_name="", generated_at=_utc_now_iso())

    rollup = Rollup(project_name=project.name, generated_at=_utc_now_iso())

    repos_manifest = project.repos or []
    for entry in repos_manifest:
        # `id` is the canonical key, but tolerate `alias` (Coda-generated
        # plan.yaml files have used this) and `name` as fallbacks so a
        # mistyped manifest doesn't silently produce an empty rollup.
        repo_id = str(entry.get("id") or entry.get("alias") or entry.get("name") or "")
        repo_path = str(entry.get("path") or "")
        role = str(entry.get("role") or "")
        if not repo_id or not repo_path:
            continue
        target = (paths.repo / repo_path).resolve()
        if not target.is_dir():
            # Real error — manifest points at a non-existent directory.
            rollup.repos.append(RepoSummary(
                id=repo_id, path=repo_path, role=role,
                open=0, frozen=0, last_touched="", last_actor="",
                contracts_index_path="",
                note=f"path missing: {repo_path}",
                is_error=True,
            ))
            continue
        rollup.repos.append(_summarize_repo(target, repo_id, repo_path, role))

    return rollup


def render_markdown(rollup: Rollup) -> str:
    """Render the rollup as the Tier-1 contracts.md content."""
    lines: list[str] = [
        "<!-- GENERATED by dotagent — do not edit. "
        "Run `dotagent project contracts --all-repos --rebuild` to refresh. -->",
        f"# Contracts across `{rollup.project_name}`",
        "",
        f"_Last generated: {rollup.generated_at}_  ·  "
        f"**{rollup.total_open} open**  ·  "
        f"**{rollup.total_frozen} frozen**",
        "",
    ]
    if not rollup.repos:
        lines.append(
            "_No `repos:` declared in `.agent/project/plan.yaml`. "
            "Add the manifest to populate this rollup._"
        )
        return "\n".join(lines) + "\n"

    lines.append(
        "| Repo | Role | Open | Frozen | Last touched | By | Where to look |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for r in rollup.repos:
        if r.is_error:
            lines.append(
                f"| **{r.id}** | {r.role or '—'} | — | — | — | — | "
                f"_⚠ error: {r.note}_ |"
            )
            continue
        if r.note and not (r.open or r.frozen):
            # Informational note (e.g. service repo without local cycles) —
            # not a failure. Render zero counts + the note as a footnote.
            lines.append(
                f"| **{r.id}** | {r.role or '—'} | 0 | 0 | — | — | "
                f"_{r.note}_ |"
            )
            continue
        link = (f"[CONTRACTS.md]({r.contracts_index_path})"
                if r.contracts_index_path else "_(no index yet)_")
        lines.append(
            f"| **{r.id}** | {r.role or '—'} | {r.open} | {r.frozen} | "
            f"{r.last_touched or '—'} | {r.last_actor or '—'} | {link} |"
        )
    return "\n".join(lines).rstrip() + "\n"


def regenerate(paths: Paths) -> Path:
    """Write the rollup to `Project Root/contracts.md`."""
    target = paths.repo / "contracts.md"
    rollup = build_rollup(paths)
    target.write_text(render_markdown(rollup))
    return target


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _summarize_repo(target_dir: Path, repo_id: str,
                    repo_path: str, role: str) -> RepoSummary:
    """Load that repo's project + build its contracts index; summarize."""
    target_paths = Paths(repo=target_dir)
    try:
        project = load_project(target_paths)
    except Exception as exc:
        # Genuine load failure — surfacing as an error helps the user
        # diagnose corrupted plan.yaml.
        return RepoSummary(
            id=repo_id, path=repo_path, role=role,
            open=0, frozen=0, last_touched="", last_actor="",
            contracts_index_path="",
            note=f"could not load project: {exc}",
            is_error=True,
        )
    if project is None:
        # Service repo doesn't run its own per-repo cycle. Valid for the
        # "single-project-with-service-repos-as-checkouts" topology (Aigent's
        # default). Informational, NOT an error.
        agent_present = (target_dir / ".agent").is_dir()
        if agent_present:
            note = "no cycles tracked here — meta tier owns project state"
        else:
            note = "no dotagent install in this service repo"
        return RepoSummary(
            id=repo_id, path=repo_path, role=role,
            open=0, frozen=0, last_touched="", last_actor="",
            contracts_index_path="",
            note=note,
            is_error=False,
        )

    index = build_index(project)
    # Find last touched timestamp across all rows
    last_touched, last_actor = _latest_touch(index)
    index_path = f"{repo_path.rstrip('/')}/.agent/project/CONTRACTS.md"

    return RepoSummary(
        id=repo_id, path=repo_path, role=role,
        open=index.total_open,
        frozen=index.total_frozen,
        last_touched=last_touched, last_actor=last_actor,
        contracts_index_path=index_path,
    )


def _latest_touch(index: ContractsIndex) -> tuple[str, str]:
    """Find the most recent (last_touched, last_actor) across the index."""
    latest_ts = ""
    latest_actor = ""
    for section in index.sections:
        for row in section.rows:
            if row.last_touched and row.last_touched > latest_ts:
                latest_ts = row.last_touched
                latest_actor = row.last_actor
    return latest_ts, latest_actor


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


__all__ = (
    "RepoSummary", "Rollup",
    "build_rollup", "render_markdown", "regenerate",
)
