"""Tier-2 contract dashboard: per-repo `.agent/project/CONTRACTS.md`.

Auto-generated. Lists every module's contracts (open + frozen) with
direct paths to the cycle files. Regenerated on every project event:
init_contract, advance_round, freeze_contract, add_module.

Pure function over Project + Module state — no LLM, no filesystem
discovery beyond reading module.yaml files (which the caller already
has loaded).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from ..paths import Paths
from .model import Module, Project


# Module-state ordering — open work first, shipped last.
_STATE_PRIORITY = {
    "in_progress": 0,
    "dev_complete": 1,
    "qa_passed": 2,
    "qa_failed": 3,
    "blocked": 4,
    "planned": 5,
    "defined": 6,
    "shipped": 7,
}


@dataclass
class ContractRow:
    """One row in the per-cycle table."""
    cycle_n: int
    state: str          # "open" | "frozen"
    round: int
    last_touched: str
    last_actor: str
    path: str           # repo-relative

    def to_dict(self) -> dict:
        return {
            "cycle": self.cycle_n,
            "state": self.state,
            "round": self.round,
            "last_touched": self.last_touched,
            "last_actor": self.last_actor,
            "path": self.path,
        }


@dataclass
class ModuleSection:
    """One module's contracts (header + rows)."""
    module_id: str
    module_name: str
    state: str
    cross_module: str           # if this is a slice of a cross-service module
    implements_features: list[str]
    rows: list[ContractRow]

    @property
    def n_open(self) -> int:
        return sum(1 for r in self.rows if r.state == "open")

    @property
    def n_frozen(self) -> int:
        return sum(1 for r in self.rows if r.state == "frozen")

    def to_dict(self) -> dict:
        return {
            "module_id": self.module_id,
            "module_name": self.module_name,
            "state": self.state,
            "cross_module": self.cross_module,
            "implements_features": list(self.implements_features),
            "rows": [r.to_dict() for r in self.rows],
            "n_open": self.n_open,
            "n_frozen": self.n_frozen,
        }


@dataclass
class ContractsIndex:
    """Materialized index over a project's contracts."""
    project_name: str
    generated_at: str
    sections: list[ModuleSection]

    @property
    def total_open(self) -> int:
        return sum(s.n_open for s in self.sections)

    @property
    def total_frozen(self) -> int:
        return sum(s.n_frozen for s in self.sections)

    def to_dict(self) -> dict:
        return {
            "project_name": self.project_name,
            "generated_at": self.generated_at,
            "total_open": self.total_open,
            "total_frozen": self.total_frozen,
            "sections": [s.to_dict() for s in self.sections],
        }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_index(project: Project) -> ContractsIndex:
    """Walk every module's cycles; return a materialized index."""
    sections: list[ModuleSection] = []
    modules = list(project.modules.values())
    modules.sort(key=lambda m: (_STATE_PRIORITY.get(m.state, 99), m.id))

    for mod in modules:
        sections.append(_section_for(mod))

    return ContractsIndex(
        project_name=project.name,
        generated_at=_utc_now_iso(),
        sections=sections,
    )


def render_markdown(index: ContractsIndex) -> str:
    """Render the index as the canonical CONTRACTS.md content."""
    lines: list[str] = [
        "<!-- GENERATED by dotagent — do not edit. "
        "Regenerated on every contract operation. Run "
        "`dotagent project contracts --rebuild` to refresh manually. -->",
        f"# Contracts in `{index.project_name}`",
        "",
        f"_Last generated: {index.generated_at}_  ·  "
        f"**{index.total_open} open**  ·  "
        f"**{index.total_frozen} frozen**",
        "",
    ]
    if not index.sections:
        lines.append("_No modules yet. Run `dotagent project add-module` to start._")
        return "\n".join(lines) + "\n"

    for section in index.sections:
        head = f"## {section.module_id}  ·  status: {section.state}"
        annotations = []
        if section.implements_features:
            annotations.append(f"implements {', '.join(section.implements_features)}")
        if section.cross_module:
            annotations.append(f"cross-module: {section.cross_module}")
        if annotations:
            head += "  ·  " + "  ·  ".join(annotations)
        lines.append(head)
        if section.module_name and section.module_name != section.module_id:
            lines.append(f"_{section.module_name}_")
        lines.append("")
        if not section.rows:
            lines.append("_(no cycles started yet)_")
            lines.append("")
            continue
        lines.append("| Cycle | State | Round | Last touched | By | Path |")
        lines.append("|---|---|---|---|---|---|")
        for row in section.rows:
            state_glyph = "✓ frozen" if row.state == "frozen" else "⏳ open"
            lines.append(
                f"| {row.cycle_n:02d} | {state_glyph} | {row.round} | "
                f"{row.last_touched} | {row.last_actor} | "
                f"[{Path(row.path).name}](./{row.path}) |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def regenerate(paths: Paths, project: Project) -> Path:
    """Materialize the index to `.agent/project/CONTRACTS.md`. Returns the path."""
    paths.project_dir.mkdir(parents=True, exist_ok=True)
    target = paths.project_dir / "CONTRACTS.md"
    index = build_index(project)
    target.write_text(render_markdown(index))
    return target


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _section_for(mod: Module) -> ModuleSection:
    rows: list[ContractRow] = []
    for cycle in mod.cycles:
        contract = cycle.contract
        if contract is None:
            continue
        state = "frozen" if str(contract.status).lower() == "frozen" else "open"
        rows.append(ContractRow(
            cycle_n=cycle.n,
            state=state,
            round=int(contract.round or 0),
            last_touched=str(contract.frozen_at or cycle.handoff_at or cycle.started_at or ""),
            last_actor=str(contract.last_actor or contract.frozen_by or ""),
            # Path is repo-relative from .agent/project/, so two ups + the contract path:
            path=f"../../{contract.path}",
        ))
    rows.sort(key=lambda r: r.cycle_n)
    return ModuleSection(
        module_id=mod.id,
        module_name=mod.name,
        state=mod.state,
        cross_module=mod.cross_module,
        implements_features=list(mod.implements_features),
        rows=rows,
    )


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


__all__ = (
    "ContractRow", "ModuleSection", "ContractsIndex",
    "build_index", "render_markdown", "regenerate",
)
