from __future__ import annotations

from .base import Adapter, RenderedFile

_HEADER = "<!-- generated by dotagent — edit .agent/*.md instead -->\n\n"


class ClaudeAdapter(Adapter):
    name = "claude"

    def render(self, source: dict) -> list[RenderedFile]:
        body = (
            f"{_HEADER}# Project context for Claude Code\n\n"
            f"## Style\n\n{source['style']}\n\n"
            f"## Rules\n\n{source['rules']}\n\n"
            f"## Architecture\n\n{source['architecture']}\n\n"
            f"## Patterns\n\n{source['patterns']}\n\n"
            f"## Preferences\n\n{source['preferences']}\n"
        )
        return [
            RenderedFile(self.paths.repo / "CLAUDE.md", body),
            RenderedFile(self.paths.adapters / "claude" / "CLAUDE.md", body),
        ]
