from __future__ import annotations

from .base import Adapter, RenderedFile


class CopilotAdapter(Adapter):
    name = "copilot"

    def render(self, source: dict) -> list[RenderedFile]:
        body = (
            "<!-- generated by dotagent — edit .agent/*.md instead -->\n\n"
            "# Copilot project instructions\n\n"
            f"## Style\n\n{source['style']}\n\n"
            f"## Rules\n\n{source['rules']}\n\n"
            f"## Architecture\n\n{source['architecture']}\n\n"
            f"## Patterns\n\n{source['patterns']}\n\n"
            f"## Preferences\n\n{source['preferences']}\n"
        )
        return [
            RenderedFile(self.paths.repo / ".github" / "copilot-instructions.md", body),
            RenderedFile(self.paths.adapters / "copilot" / "copilot-instructions.md", body),
        ]
