from __future__ import annotations

from .base import Adapter, RenderedFile


class CursorAdapter(Adapter):
    name = "cursor"

    def render(self, source: dict) -> list[RenderedFile]:
        body = (
            "# .cursorrules — generated by dotagent (edit .agent/*.md instead)\n\n"
            f"## Coding style\n\n{source['style']}\n\n"
            f"## Rules\n\n{source['rules']}\n\n"
            f"## Architecture\n\n{source['architecture']}\n\n"
            f"## Patterns\n\n{source['patterns']}\n\n"
            f"## Preferences\n\n{source['preferences']}\n"
        )
        return [
            RenderedFile(self.paths.repo / ".cursorrules", body),
            RenderedFile(self.paths.adapters / "cursor" / ".cursorrules", body),
        ]
