from __future__ import annotations

from .base import Adapter, RenderedFile


class OpenCodeAdapter(Adapter):
    name = "opencode"

    def render(self, source: dict) -> list[RenderedFile]:
        body = (
            "<!-- generated by dotagent — edit .agent/*.md instead -->\n\n"
            "# AGENTS.md\n\n"
            f"## Style\n\n{source['style']}\n\n"
            f"## Rules\n\n{source['rules']}\n\n"
            f"## Architecture\n\n{source['architecture']}\n\n"
            f"## Patterns\n\n{source['patterns']}\n\n"
            f"## Preferences\n\n{source['preferences']}\n"
        )
        return [
            RenderedFile(self.paths.repo / "AGENTS.md", body),
            RenderedFile(self.paths.adapters / "opencode" / "AGENTS.md", body),
        ]
