"""Shared body builder for adapter outputs.

Every adapter (CLAUDE.md, .cursorrules, copilot, AGENTS.md) renders the same
context: project rules, indexed bug registry, anti-patterns, redis/DB hotspots,
dependency map, architecture, personal style for the active actor, and a
recent-activity feed. The wrapper differs per tool; the body is unified.
"""

from __future__ import annotations

from typing import Any

from ..context import Context
from ..sources import IndexedSource, SourceEntry


_HEADER_NOTE = "<!-- generated by dotagent — DO NOT EDIT directly. Edit `.agent/*.md` or `docs/*.md` (sources of truth). Re-render with `dotagent sync`. -->"


def render_body(ctx: Context, *, tool_label: str = "AI coding agent") -> str:
    """Return the fully-rendered markdown body for an adapter file."""
    parts: list[str] = []
    parts.append(_HEADER_NOTE)
    parts.append("")
    parts.append(f"# Project context for {tool_label} — `{ctx.project_name}`")
    parts.append("")
    parts.append(_render_overview(ctx))
    parts.append(_render_brief_excerpt(ctx))
    parts.append(_render_project(ctx))
    parts.append(_render_conflicts(ctx))
    parts.append(_render_stale_rules_warning(ctx))
    parts.append(_render_rules(ctx))
    parts.append(_render_bug_registry(ctx))
    parts.append(_render_anti_patterns(ctx))
    parts.append(_render_db_impact(ctx))
    parts.append(_render_redis_keys(ctx))
    parts.append(_render_dependency_map(ctx))
    parts.append(_render_architecture(ctx))
    parts.append(_render_style(ctx))
    parts.append(_render_patterns(ctx))
    parts.append(_render_personal(ctx))
    parts.append(_render_current_state(ctx))
    parts.append(_render_recent_activity(ctx))
    parts.append(_render_sources_footer(ctx))
    return "\n\n".join(p for p in parts if p).rstrip() + "\n"


# -- sections ----------------------------------------------------------------


def _render_overview(ctx: Context) -> str:
    indexed = [s for s in ctx.sources.values() if s.exists]
    missing = [s for s in ctx.sources.values() if not s.exists]
    lines = ["## Overview", ""]
    if ctx.actor:
        lines.append(f"- Active developer: **{ctx.actor}**")
    if ctx.current.branch:
        lines.append(f"- Current branch: `{ctx.current.branch}`")
    if ctx.current.task:
        lines.append(f"- Current task: {ctx.current.task}")
    lines.append(f"- Indexed sources: {len(indexed)} present, {len(missing)} missing")
    if indexed:
        for s in indexed:
            lines.append(f"  - `{s.path}` — {s.summary}")
    if missing:
        lines.append("")
        lines.append("_Missing sources (configure or create to enrich agent context):_")
        for s in missing:
            lines.append(f"  - `{s.path}`")
    return "\n".join(lines)


def _render_project(ctx: Context) -> str:
    """Phase 8: project management. Surfaces active module + the right doc per state."""
    project = ctx.project_plan
    if not project:
        return ""
    try:
        from ..project.model import ModuleState
    except ImportError:
        return ""

    lines = [f"## Project: `{project.name}`", ""]
    if project.goal:
        lines.append(f"_Goal:_ {project.goal}")
        lines.append("")

    shipped = [m.id for m in project.modules.values() if m.state == ModuleState.SHIPPED]
    in_prog = [m.id for m in project.modules.values() if m.state == ModuleState.IN_PROGRESS]
    devdone = [m.id for m in project.modules.values() if m.state == ModuleState.DEV_COMPLETE]
    qapass = [m.id for m in project.modules.values() if m.state == ModuleState.QA_PASSED]
    blocked = [m.id for m in project.modules.values() if m.state == ModuleState.BLOCKED]
    planned = [m.id for m in project.modules.values() if m.state in (
        ModuleState.PLANNED, ModuleState.DEFINED,
    )]
    total = len(project.modules) or 1
    pct = (len(shipped) / total) * 100

    lines.append(f"**Progress:** {len(shipped)}/{len(project.modules)} modules shipped ({pct:.0f}%)")
    if shipped:
        lines.append(f"- ★ shipped:      {', '.join(shipped)}")
    if qapass:
        lines.append(f"- ✓ qa_passed:    {', '.join(qapass)}")
    if devdone:
        lines.append(f"- ▸ dev_complete: {', '.join(devdone)}")
    if in_prog:
        lines.append(f"- ▶ in_progress:  {', '.join(in_prog)}")
    if planned:
        lines.append(f"- ○ planned:      {', '.join(planned)}")
    if blocked:
        lines.append(f"- ⊘ blocked:      {', '.join(blocked)}")

    # Active module focus: surfaces the right document based on state.
    mid = ctx.project_active_module_id
    if mid and mid in project.modules:
        mod = project.modules[mid]
        lines.append("")
        lines.append(f"### → Active module: `{mid}` ({mod.state})")
        if mod.plan and mod.plan.purpose:
            lines.append(f"_{mod.plan.purpose}_")
        if mod.plan and mod.plan.acceptance_criteria:
            lines.append("")
            lines.append("**Acceptance criteria:**")
            for c in mod.plan.acceptance_criteria[:8]:
                lines.append(f"- [ ] {c}")
            if len(mod.plan.acceptance_criteria) > 8:
                lines.append(f"- _(+{len(mod.plan.acceptance_criteria) - 8} more — see `.agent/project/modules/{mid}/PLAN.md`)_")

        doc_to_read = _active_doc_pointer(mid, mod)
        if doc_to_read:
            lines.append("")
            lines.append(f"**Read next:** `{doc_to_read[0]}` — _{doc_to_read[1]}_")

    return "\n".join(lines)


def _active_doc_pointer(mid: str, mod) -> tuple[str, str] | None:
    """Return (path, why) for the document the AI agent should read next based on state."""
    try:
        from ..project.model import ModuleState
    except ImportError:
        return None
    base = f".agent/project/modules/{mid}"
    if mod.state == ModuleState.IN_PROGRESS:
        # if last cycle had qa-fail, point at the findings to address
        last_qa = mod.last_qa_result
        if last_qa and not last_qa.passed:
            return (
                f"{base}/cycles/{last_qa.cycle:02d}/qa-findings.md",
                "QA findings from the previous cycle — address these, then `dotagent project handoff` again",
            )
        return (f"{base}/PLAN.md", "the module plan you're building against")
    if mod.state == ModuleState.DEV_COMPLETE:
        n = mod.current_cycle.n if mod.current_cycle else 1
        return (
            f"{base}/cycles/{n:02d}/dev-handoff.md",
            "dev handoff awaiting QA — read this if you are the QA tool, follow the QA prompt at the bottom",
        )
    if mod.state == ModuleState.QA_PASSED:
        return (f"{base}/PLAN.md", "QA passed — confirm acceptance criteria, then `dotagent project resolve`")
    return (f"{base}/PLAN.md", "the module plan")


def _render_conflicts(ctx: Context) -> str:
    """Module 1: warn when active working-memory files overlap with rules citing them.

    Section is suppressed entirely when there are no conflicts. This must not
    add noise — it's only valuable when it has something to say.
    """
    rows = ctx.detect_conflicts()
    if not rows:
        return ""
    lines = [
        "## ⚠ Rule conflicts in active edits",
        "",
        "_The files you're currently editing are cited by these rules. "
        "Review each before the next handoff — these are not informational; "
        "they are constraints on the change you're making._",
        "",
    ]
    sev_marker = {
        "critical": "🔴 CRITICAL", "high": "🟠 HIGH",
        "medium": "🟡 MEDIUM", "low": "⚪ LOW",
        "p0": "🔴 P0", "p1": "🟠 P1", "p2": "🟡 P2", "p3": "⚪ P3",
        "": "⚪ —", "unknown": "⚪ —",
    }
    for r in rows:
        sev = sev_marker.get(r["severity"], "⚪ —")
        files = ", ".join(f"`{f}`" for f in r["all_touched_files"][:3])
        lines.append(f"- **{r['id']}** — {sev} — _{r['kind']}_ — {r['title']}")
        lines.append(f"  - Touched in this session: {files}")
        lines.append(f"  - Source: `{r['source_path']}`")
        lines.append(f"  - Action: {r['what_to_do']}")
    return "\n".join(lines)


def _render_stale_rules_warning(ctx: Context) -> str:
    """Module 2: surface a count of rules due for review.

    Cheap nudge — the full list lives behind `dotagent dream review-stale`.
    Suppressed entirely when no rules are stale.
    """
    if not ctx.semantic_pointer_cards and not _has_graduated_rules(ctx):
        return ""
    try:
        from ..dream.lifecycle import review_stale
        from ..paths import Paths
        # Need a Paths object — reconstruct from repo_path
        from pathlib import Path
        paths = Paths(repo=Path(ctx.repo_path))
        stale = review_stale(paths, include_due_soon_days=14)
    except Exception:
        return ""
    if not stale:
        return ""
    past = [s for s in stale if s.reason in ("review_after_passed", "legacy_no_metadata", "cited_files_churned")]
    due_soon = [s for s in stale if s.reason == "due_soon"]
    lines = ["## ⚠ Rule lifecycle"]
    lines.append("")
    if past:
        lines.append(f"- **{len(past)} rule(s) overdue for review** — they may no longer reflect "
                     f"the current codebase.")
    if due_soon:
        lines.append(f"- {len(due_soon)} rule(s) due for review in the next 14 days.")
    lines.append("")
    lines.append("Run `dotagent dream review-stale` for the list; "
                 "`dotagent dream rerationale <id> --rationale \"...\"` to extend each, "
                 "`dotagent dream expire-stale` to retire past-grace rules.")
    return "\n".join(lines)


def _has_graduated_rules(ctx: Context) -> bool:
    """Heuristic — do we even have graduated rules to warn about?"""
    from pathlib import Path
    sem = Path(ctx.repo_path) / ".agent" / "memory" / "semantic"
    if not sem.exists():
        return False
    try:
        return any(p.is_file() for p in sem.rglob("*.md") if "expired" not in p.parts and "sources" not in p.parts)
    except OSError:
        return False


def _render_rules(ctx: Context) -> str:
    body = (ctx.agent.rules or "").strip()
    if not body:
        return ""
    return "## Project rules (hard constraints)\n\n" + body


def _render_bug_registry(ctx: Context) -> str:
    bugs = ctx.top_bugs()
    src = ctx.sources.get("bug_registry")
    if not bugs:
        if src and not src.exists:
            return (
                "## Bug registry\n\n"
                f"_No `{src.path}` found. Create it and re-run `dotagent sync` to surface "
                f"known bugs to every AI agent._"
            )
        return ""
    lines = ["## Bug registry — known bugs to avoid", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary}). Top {len(bugs)} shown; full list in source._")
        lines.append("")
    for b in bugs:
        lines.append(_format_entry(b, prefix="BUG"))
    return "\n".join(lines)


def _render_anti_patterns(ctx: Context) -> str:
    aps = ctx.top_anti_patterns()
    src = ctx.sources.get("anti_patterns")
    if not aps:
        if src and not src.exists:
            return ""
        return ""
    lines = ["## Anti-patterns — do not introduce these", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for a in aps:
        lines.append(_format_entry(a, prefix="ANTI"))
    return "\n".join(lines)


def _render_db_impact(ctx: Context) -> str:
    entries = ctx.db_impact()
    src = ctx.sources.get("db_impact_map")
    if not entries:
        return ""
    lines = ["## Database impact map — tables/columns to handle with care", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        ts = ", ".join(f"`{t}`" for t in e.tables[:8])
        head = f"- **{e.id}** {e.title}"
        if ts:
            head += f" — tables: {ts}"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_redis_keys(ctx: Context) -> str:
    entries = ctx.redis_keys()
    src = ctx.sources.get("redis_keys")
    if not entries:
        return ""
    lines = ["## Redis keys — patterns and ownership", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        keys = ", ".join(f"`{k}`" for k in e.keys[:6])
        head = f"- **{e.id}** {e.title}"
        if keys:
            head += f" — keys: {keys}"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_dependency_map(ctx: Context) -> str:
    entries = ctx.dependency_map()
    src = ctx.sources.get("dependency_map")
    if not entries:
        return ""
    lines = ["## Dependency map — which services touch what", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        comps = " → ".join(e.components) if e.components else ""
        head = f"- **{e.id}** {e.title}"
        if comps:
            head += f" — `{comps}`"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_architecture(ctx: Context) -> str:
    arch_src = ctx.sources.get("architecture")
    sections = ctx.architecture_sections()
    body_md = (ctx.agent.architecture or "").strip()
    if not sections and not body_md:
        return ""
    lines = ["## Architecture", ""]
    if arch_src and arch_src.exists:
        lines.append(f"_Detailed architecture lives in `{arch_src.path}`._")
        lines.append("")
        for s in sections[:12]:
            lines.append(f"- **{s.title}** — {_one_line(s.body, 200)}")
    if body_md:
        lines.append("")
        lines.append(body_md)
    return "\n".join(lines)


def _render_style(ctx: Context) -> str:
    body = (ctx.agent.style or "").strip()
    if not body:
        return ""
    return "## Coding style\n\n" + body


def _render_patterns(ctx: Context) -> str:
    body = (ctx.agent.patterns or "").strip()
    if not body:
        return ""
    return "## Patterns (graduated knowledge)\n\n" + body


def _render_personal(ctx: Context) -> str:
    if not ctx.actor or not ctx.personal:
        return ""
    lines = [f"## Personal preferences for `{ctx.actor}`", ""]
    for k, v in ctx.personal.items():
        if isinstance(v, list):
            lines.append(f"- **{k}**: " + ", ".join(str(x) for x in v))
        else:
            lines.append(f"- **{k}**: {v}")
    body = (ctx.agent.preferences or "").strip()
    if body:
        lines.append("")
        lines.append("### Project-wide preferences")
        lines.append("")
        lines.append(body)
    return "\n".join(lines)


def _render_current_state(ctx: Context) -> str:
    cs = ctx.current
    if not cs.session and not cs.recent_files and not cs.task:
        return ""
    lines = ["## Working memory — what's happening now", ""]
    if cs.session:
        lines.append(f"- Session: `{cs.session}` (tool: `{cs.tool or 'unknown'}`)")
    if cs.branch:
        lines.append(f"- Branch: `{cs.branch}`")
    if cs.task:
        lines.append(f"- Task: {cs.task}")
    if cs.recent_files:
        lines.append("- Recent files:")
        for f in cs.recent_files[:10]:
            lines.append(f"  - `{f}`")
    return "\n".join(lines)


def _render_recent_activity(ctx: Context) -> str:
    if not ctx.recent_episodic:
        return ""
    lines = ["## Recent activity (episodic memory)", ""]
    for e in ctx.recent_episodic:
        ts = (e.get("ts") or "").split("T", 1)[0]
        actor = e.get("actor") or "?"
        tool = e.get("tool") or "?"
        kind = e.get("kind") or "event"
        summary = (e.get("summary") or "").strip()
        files = e.get("files") or []
        head = f"- {ts} · `{actor}` via `{tool}` · **{kind}**"
        if summary:
            head += f" — {_one_line(summary, 160)}"
        lines.append(head)
        if files:
            lines.append(f"  files: " + ", ".join(f"`{f}`" for f in files[:5]))
    return "\n".join(lines)


def _render_sources_footer(ctx: Context) -> str:
    if not ctx.sources:
        return ""
    lines = ["---", "", "## Source pointers", ""]
    lines.append("_The agent should fetch the full file when it needs more than the summary above._")
    lines.append("")
    for name, src in sorted(ctx.sources.items()):
        flag = "" if src.exists else " _(missing)_"
        lines.append(f"- **{name}** → `{src.path}` — {src.summary}{flag}")
    return "\n".join(lines)


# -- formatting helpers ------------------------------------------------------


def _format_entry(e: SourceEntry, *, prefix: str = "") -> str:
    head_id = f"{prefix}-{e.id}" if prefix and not e.id.startswith(prefix) else e.id
    sev = f" [{e.severity}]" if e.severity else ""
    head = f"### {head_id}{sev} — {e.title}"
    lines = [head]
    if e.files:
        lines.append("- Files: " + ", ".join(f"`{f}`" for f in e.files[:6]))
    if e.components:
        lines.append("- Components: " + ", ".join(f"`{c}`" for c in e.components[:6]))
    if e.tables:
        lines.append("- Tables: " + ", ".join(f"`{t}`" for t in e.tables[:6]))
    if e.keys:
        lines.append("- Keys: " + ", ".join(f"`{k}`" for k in e.keys[:6]))
    if getattr(e, "cross_references", None):
        lines.append("- Cross-refs: " + ", ".join(f"`{r}`" for r in e.cross_references[:6]))
    if e.body:
        lines.append("")
        lines.append(_one_line(e.body, 600))
    return "\n".join(lines)


def _one_line(text: str, max_len: int) -> str:
    s = " ".join(text.split())
    if len(s) <= max_len:
        return s
    return s[: max_len - 1].rstrip() + "…"


def coerce_to_context(arg: Any, paths) -> Context:
    """Adapters accept either a Context (new) or a dict-of-strings (legacy).

    Legacy dicts get wrapped into a minimal Context so old callsites still work.
    """
    if isinstance(arg, Context):
        return arg
    if isinstance(arg, dict):
        from ..context import AgentSources
        from ..memory.working import CurrentState
        return Context(
            project_name=paths.repo.name,
            actor="",
            repo_path=str(paths.repo),
            agent=AgentSources(
                style=arg.get("style", ""),
                rules=arg.get("rules", ""),
                architecture=arg.get("architecture", ""),
                patterns=arg.get("patterns", ""),
                preferences=arg.get("preferences", ""),
            ),
            sources={},
            semantic_pointer_cards=[],
            personal={},
            current=CurrentState(actor=""),
            recent_episodic=[],
            config_top_n={},
        )
    raise TypeError(f"Unsupported adapter source: {type(arg)!r}")


# ---------------------------------------------------------------------------
# PR #7: brief excerpt — selective embed of project_brief.md
# ---------------------------------------------------------------------------

def _render_brief_excerpt(ctx: Context) -> str:
    """Render the structured subset of project_brief.md.

    Selective rule:
    - All OBJ-IDs + titles (every repo sees the project objectives)
    - All FEAT-IDs + names (filtered to this-repo's modules once the
      layered structure ships in PR #11; today: all features)
    - All hard rules (RULE-NN) — project-wide enforcement
    - Glossary, tenancy, non-goals (project-wide)

    Returns empty string when there's no brief — preserving v0.3 behavior.
    """
    brief = getattr(ctx, "brief", None)
    if brief is None:
        return ""

    lines: list[str] = ["## Project context (from `.agent/project_brief.md`)"]
    meta_bits = []
    if brief.brief_version:
        meta_bits.append(f"brief version {brief.brief_version}")
    if brief.last_reviewed:
        meta_bits.append(f"last reviewed {brief.last_reviewed}")
    if brief.stage:
        meta_bits.append(f"stage: {brief.stage}")
    if meta_bits:
        lines.append("")
        lines.append("_" + " · ".join(meta_bits) + "_")

    if brief.vision:
        lines.append("")
        lines.append(f"**Vision:** {brief.vision}")

    if brief.objectives:
        lines.append("")
        lines.append("**Business objectives:**")
        for o in brief.objectives:
            lines.append(f"- **{o.id}**: {o.text}")

    if brief.features:
        repo_features = _features_for_this_repo(ctx, brief)
        lines.append("")
        lines.append(f"**Features implemented here ({len(repo_features)}):**")
        for f in repo_features:
            serves = ", ".join(f.serves) if f.serves else "(none)"
            lines.append(f"- **{f.id}** ({f.name}) — serves {serves}")
            if f.expected_outcome:
                lines.append(f"  · _outcome: {f.expected_outcome}_")

    if brief.hard_rules:
        lines.append("")
        lines.append("**Hard rules (do not violate):**")
        for r in brief.hard_rules:
            why = f" — _why: {r.why}_" if r.why else ""
            lines.append(f"- **{r.id} · {r.name}**{why}")

    if brief.tenancy_lines:
        lines.append("")
        lines.append("**Tenancy & security posture:**")
        for line in brief.tenancy_lines:
            lines.append(f"- {line}")

    if brief.non_goals:
        lines.append("")
        lines.append("**Non-goals (do NOT propose work in these areas):**")
        for ng in brief.non_goals:
            lines.append(f"- {ng}")

    if brief.constraints:
        lines.append("")
        lines.append("**Constraints:**")
        for c in brief.constraints:
            lines.append(f"- {c}")

    if brief.glossary:
        lines.append("")
        lines.append("**Glossary:**")
        for term, defn in brief.glossary:
            lines.append(f"- **{term}** — {defn}")

    if brief.integrations:
        lines.append("")
        lines.append("**External integrations:**")
        for it in brief.integrations:
            used = ", ".join(it.used_by) if it.used_by else "(none)"
            lines.append(
                f"- **{it.vendor}** — {it.purpose or '(no purpose)'} · "
                f"used by {used} · auth: {it.auth or 'n/a'}"
            )

    lines.append("")
    lines.append("_Full brief: `.agent/project_brief.md`. "
                 "Hand-written; rarely changes. Re-render with `dotagent sync`._")
    return "\n".join(lines)


def _features_for_this_repo(ctx: Context, brief) -> list:
    """Filter brief.features to those implemented by THIS repo's modules.

    Filter rule:
    - If the project plan declares `features_to_modules`, use it as the
      authority: feature included iff any module mapped to it lives in
      this repo (modules in the project_plan implicitly do).
    - Otherwise, return all features (single-repo / unconfigured case).
    """
    if not getattr(ctx, "project_plan", None):
        return list(brief.features)
    proj = ctx.project_plan
    f2m = getattr(proj, "features_to_modules", None) or {}
    if not f2m:
        # No mapping yet — surface all features so nothing's hidden.
        return list(brief.features)
    relevant_feat_ids: set[str] = set()
    local_module_ids = set(getattr(proj, "module_ids", None) or [])
    for feat_id, module_ids in f2m.items():
        if any(m in local_module_ids for m in module_ids):
            relevant_feat_ids.add(feat_id)
    return [f for f in brief.features if f.id in relevant_feat_ids] or list(brief.features)
