"""Shared body builder for adapter outputs.

Every adapter (CLAUDE.md, .cursorrules, copilot, AGENTS.md) renders the same
context: project rules, indexed bug registry, anti-patterns, redis/DB hotspots,
dependency map, architecture, personal style for the active actor, and a
recent-activity feed. The wrapper differs per tool; the body is unified.
"""

from __future__ import annotations

from typing import Any

from ..context import Context
from ..sources import IndexedSource, SourceEntry


_HEADER_NOTE = "<!-- generated by dotagent — DO NOT EDIT directly. Edit `.agent/*.md` or `docs/*.md` (sources of truth). Re-render with `dotagent sync`. -->"


def render_body(ctx: Context, *, tool_label: str = "AI coding agent") -> str:
    """Return the fully-rendered markdown body for an adapter file."""
    parts: list[str] = []
    parts.append(_HEADER_NOTE)
    parts.append("")
    parts.append(f"# Project context for {tool_label} — `{ctx.project_name}`")
    parts.append("")
    parts.append(_render_overview(ctx))
    parts.append(_render_rules(ctx))
    parts.append(_render_bug_registry(ctx))
    parts.append(_render_anti_patterns(ctx))
    parts.append(_render_db_impact(ctx))
    parts.append(_render_redis_keys(ctx))
    parts.append(_render_dependency_map(ctx))
    parts.append(_render_architecture(ctx))
    parts.append(_render_style(ctx))
    parts.append(_render_patterns(ctx))
    parts.append(_render_personal(ctx))
    parts.append(_render_current_state(ctx))
    parts.append(_render_recent_activity(ctx))
    parts.append(_render_sources_footer(ctx))
    return "\n\n".join(p for p in parts if p).rstrip() + "\n"


# -- sections ----------------------------------------------------------------


def _render_overview(ctx: Context) -> str:
    indexed = [s for s in ctx.sources.values() if s.exists]
    missing = [s for s in ctx.sources.values() if not s.exists]
    lines = ["## Overview", ""]
    if ctx.actor:
        lines.append(f"- Active developer: **{ctx.actor}**")
    if ctx.current.branch:
        lines.append(f"- Current branch: `{ctx.current.branch}`")
    if ctx.current.task:
        lines.append(f"- Current task: {ctx.current.task}")
    lines.append(f"- Indexed sources: {len(indexed)} present, {len(missing)} missing")
    if indexed:
        for s in indexed:
            lines.append(f"  - `{s.path}` — {s.summary}")
    if missing:
        lines.append("")
        lines.append("_Missing sources (configure or create to enrich agent context):_")
        for s in missing:
            lines.append(f"  - `{s.path}`")
    return "\n".join(lines)


def _render_rules(ctx: Context) -> str:
    body = (ctx.agent.rules or "").strip()
    if not body:
        return ""
    return "## Project rules (hard constraints)\n\n" + body


def _render_bug_registry(ctx: Context) -> str:
    bugs = ctx.top_bugs()
    src = ctx.sources.get("bug_registry")
    if not bugs:
        if src and not src.exists:
            return (
                "## Bug registry\n\n"
                f"_No `{src.path}` found. Create it and re-run `dotagent sync` to surface "
                f"known bugs to every AI agent._"
            )
        return ""
    lines = ["## Bug registry — known bugs to avoid", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary}). Top {len(bugs)} shown; full list in source._")
        lines.append("")
    for b in bugs:
        lines.append(_format_entry(b, prefix="BUG"))
    return "\n".join(lines)


def _render_anti_patterns(ctx: Context) -> str:
    aps = ctx.top_anti_patterns()
    src = ctx.sources.get("anti_patterns")
    if not aps:
        if src and not src.exists:
            return ""
        return ""
    lines = ["## Anti-patterns — do not introduce these", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for a in aps:
        lines.append(_format_entry(a, prefix="ANTI"))
    return "\n".join(lines)


def _render_db_impact(ctx: Context) -> str:
    entries = ctx.db_impact()
    src = ctx.sources.get("db_impact_map")
    if not entries:
        return ""
    lines = ["## Database impact map — tables/columns to handle with care", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        ts = ", ".join(f"`{t}`" for t in e.tables[:8])
        head = f"- **{e.id}** {e.title}"
        if ts:
            head += f" — tables: {ts}"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_redis_keys(ctx: Context) -> str:
    entries = ctx.redis_keys()
    src = ctx.sources.get("redis_keys")
    if not entries:
        return ""
    lines = ["## Redis keys — patterns and ownership", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        keys = ", ".join(f"`{k}`" for k in e.keys[:6])
        head = f"- **{e.id}** {e.title}"
        if keys:
            head += f" — keys: {keys}"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_dependency_map(ctx: Context) -> str:
    entries = ctx.dependency_map()
    src = ctx.sources.get("dependency_map")
    if not entries:
        return ""
    lines = ["## Dependency map — which services touch what", ""]
    if src and src.exists:
        lines.append(f"_Source of truth: `{src.path}` ({src.summary})._")
        lines.append("")
    for e in entries[:25]:
        comps = " → ".join(e.components) if e.components else ""
        head = f"- **{e.id}** {e.title}"
        if comps:
            head += f" — `{comps}`"
        lines.append(head)
        if e.body:
            lines.append(f"  {_one_line(e.body, 240)}")
    return "\n".join(lines)


def _render_architecture(ctx: Context) -> str:
    arch_src = ctx.sources.get("architecture")
    sections = ctx.architecture_sections()
    body_md = (ctx.agent.architecture or "").strip()
    if not sections and not body_md:
        return ""
    lines = ["## Architecture", ""]
    if arch_src and arch_src.exists:
        lines.append(f"_Detailed architecture lives in `{arch_src.path}`._")
        lines.append("")
        for s in sections[:12]:
            lines.append(f"- **{s.title}** — {_one_line(s.body, 200)}")
    if body_md:
        lines.append("")
        lines.append(body_md)
    return "\n".join(lines)


def _render_style(ctx: Context) -> str:
    body = (ctx.agent.style or "").strip()
    if not body:
        return ""
    return "## Coding style\n\n" + body


def _render_patterns(ctx: Context) -> str:
    body = (ctx.agent.patterns or "").strip()
    if not body:
        return ""
    return "## Patterns (graduated knowledge)\n\n" + body


def _render_personal(ctx: Context) -> str:
    if not ctx.actor or not ctx.personal:
        return ""
    lines = [f"## Personal preferences for `{ctx.actor}`", ""]
    for k, v in ctx.personal.items():
        if isinstance(v, list):
            lines.append(f"- **{k}**: " + ", ".join(str(x) for x in v))
        else:
            lines.append(f"- **{k}**: {v}")
    body = (ctx.agent.preferences or "").strip()
    if body:
        lines.append("")
        lines.append("### Project-wide preferences")
        lines.append("")
        lines.append(body)
    return "\n".join(lines)


def _render_current_state(ctx: Context) -> str:
    cs = ctx.current
    if not cs.session and not cs.recent_files and not cs.task:
        return ""
    lines = ["## Working memory — what's happening now", ""]
    if cs.session:
        lines.append(f"- Session: `{cs.session}` (tool: `{cs.tool or 'unknown'}`)")
    if cs.branch:
        lines.append(f"- Branch: `{cs.branch}`")
    if cs.task:
        lines.append(f"- Task: {cs.task}")
    if cs.recent_files:
        lines.append("- Recent files:")
        for f in cs.recent_files[:10]:
            lines.append(f"  - `{f}`")
    return "\n".join(lines)


def _render_recent_activity(ctx: Context) -> str:
    if not ctx.recent_episodic:
        return ""
    lines = ["## Recent activity (episodic memory)", ""]
    for e in ctx.recent_episodic:
        ts = (e.get("ts") or "").split("T", 1)[0]
        actor = e.get("actor") or "?"
        tool = e.get("tool") or "?"
        kind = e.get("kind") or "event"
        summary = (e.get("summary") or "").strip()
        files = e.get("files") or []
        head = f"- {ts} · `{actor}` via `{tool}` · **{kind}**"
        if summary:
            head += f" — {_one_line(summary, 160)}"
        lines.append(head)
        if files:
            lines.append(f"  files: " + ", ".join(f"`{f}`" for f in files[:5]))
    return "\n".join(lines)


def _render_sources_footer(ctx: Context) -> str:
    if not ctx.sources:
        return ""
    lines = ["---", "", "## Source pointers", ""]
    lines.append("_The agent should fetch the full file when it needs more than the summary above._")
    lines.append("")
    for name, src in sorted(ctx.sources.items()):
        flag = "" if src.exists else " _(missing)_"
        lines.append(f"- **{name}** → `{src.path}` — {src.summary}{flag}")
    return "\n".join(lines)


# -- formatting helpers ------------------------------------------------------


def _format_entry(e: SourceEntry, *, prefix: str = "") -> str:
    head_id = f"{prefix}-{e.id}" if prefix and not e.id.startswith(prefix) else e.id
    sev = f" [{e.severity}]" if e.severity else ""
    head = f"### {head_id}{sev} — {e.title}"
    lines = [head]
    if e.files:
        lines.append("- Files: " + ", ".join(f"`{f}`" for f in e.files[:6]))
    if e.components:
        lines.append("- Components: " + ", ".join(f"`{c}`" for c in e.components[:6]))
    if e.tables:
        lines.append("- Tables: " + ", ".join(f"`{t}`" for t in e.tables[:6]))
    if e.keys:
        lines.append("- Keys: " + ", ".join(f"`{k}`" for k in e.keys[:6]))
    if e.body:
        lines.append("")
        lines.append(_one_line(e.body, 600))
    return "\n".join(lines)


def _one_line(text: str, max_len: int) -> str:
    s = " ".join(text.split())
    if len(s) <= max_len:
        return s
    return s[: max_len - 1].rstrip() + "…"


def coerce_to_context(arg: Any, paths) -> Context:
    """Adapters accept either a Context (new) or a dict-of-strings (legacy).

    Legacy dicts get wrapped into a minimal Context so old callsites still work.
    """
    if isinstance(arg, Context):
        return arg
    if isinstance(arg, dict):
        from ..context import AgentSources
        from ..memory.working import CurrentState
        return Context(
            project_name=paths.repo.name,
            actor="",
            repo_path=str(paths.repo),
            agent=AgentSources(
                style=arg.get("style", ""),
                rules=arg.get("rules", ""),
                architecture=arg.get("architecture", ""),
                patterns=arg.get("patterns", ""),
                preferences=arg.get("preferences", ""),
            ),
            sources={},
            semantic_pointer_cards=[],
            personal={},
            current=CurrentState(actor=""),
            recent_episodic=[],
            config_top_n={},
        )
    raise TypeError(f"Unsupported adapter source: {type(arg)!r}")
