"""Coverage gates for the CLAUDE.md navigation manifest renderer.

Three guarantees:

1. Every schema entry has a category (none default to CAT_UNCATEGORIZED).
2. Every non-hidden schema entry appears in the rendered manifest.
3. The workflow contract + hard policy + reading protocol are present
   in every tier's rendered manifest.

If any of these fail, CI blocks merge — that's the design intent.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from dotagent.canonical_structure import (
    CAT_HIDDEN,
    CAT_UNCATEGORIZED,
    TIER_PROJECT_ROOT,
    TIER_SERVICE_REPO,
    TIER_SINGLE_REPO,
    schema_for,
)
from dotagent.paths import Paths
from dotagent.render.manifest import render_manifest


_ALL_TIERS = (TIER_PROJECT_ROOT, TIER_SERVICE_REPO, TIER_SINGLE_REPO)


def _fixture_paths(tmp_path: Path) -> Paths:
    """A bare-but-valid project root for rendering tests."""
    (tmp_path / ".agent").mkdir()
    return Paths(repo=tmp_path)


# ---------------------------------------------------------------------------
# Guarantee 1: every schema entry has a category
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("tier", _ALL_TIERS)
def test_every_schema_entry_has_a_category(tier: str):
    """No SchemaEntry may default to CAT_UNCATEGORIZED. Forces every new
    entry to declare its CLAUDE.md placement."""
    schema = schema_for(tier)
    uncategorized = [e for e in schema if e.category == CAT_UNCATEGORIZED]
    assert not uncategorized, (
        f"tier={tier}: {len(uncategorized)} entry/entries lack a category. "
        f"Pick from canonical_structure.ALL_CATEGORIES or mark CAT_HIDDEN. "
        f"Offenders: {[e.path for e in uncategorized]}"
    )


# ---------------------------------------------------------------------------
# Guarantee 2: every non-hidden schema entry appears in rendered manifest
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("tier", _ALL_TIERS)
def test_every_non_hidden_entry_appears_in_manifest(tier: str, tmp_path: Path):
    """Coverage gate: the rendered manifest must contain every non-hidden
    schema entry's path. If you add a new entry to the schema, you also
    need to make sure its category is rendered."""
    paths = _fixture_paths(tmp_path)
    rendered = render_manifest(paths, tier=tier)

    missing = []
    for entry in schema_for(tier):
        if entry.category == CAT_HIDDEN:
            continue
        if entry.path not in rendered:
            missing.append((entry.path, entry.category))

    assert not missing, (
        f"tier={tier}: {len(missing)} schema entry/entries missing from manifest. "
        f"Either fix the renderer's _CATEGORY_RENDER_ORDER or mark the entry CAT_HIDDEN. "
        f"Missing: {missing}"
    )


# ---------------------------------------------------------------------------
# Guarantee 3: workflow contract + hard policy + reading protocol present
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("tier", _ALL_TIERS)
def test_workflow_contract_present_in_every_manifest(tier: str, tmp_path: Path):
    """The three invariant blocks must appear at the top of every CLAUDE.md
    regardless of tier."""
    paths = _fixture_paths(tmp_path)
    rendered = render_manifest(paths, tier=tier)

    assert "HOW TO READ THIS FILE" in rendered
    assert "WORKFLOW CONTRACT" in rendered
    assert "HARD POLICY" in rendered
    assert "MUST READ before any code edit" in rendered
    assert "MANDATORY documentation updates" in rendered


@pytest.mark.parametrize("tier", _ALL_TIERS)
def test_hard_policy_ban_phrases_present(tier: str, tmp_path: Path):
    """Specific never-violate items must remain in the rendered output
    (so future template edits can't silently weaken the policy)."""
    paths = _fixture_paths(tmp_path)
    rendered = render_manifest(paths, tier=tier)

    must_be_present = [
        "NEVER push without QA-pass",
        "NEVER use `git push --no-verify`",
        "NEVER hand-edit a file with a `<!-- generated by dotagent",
        "NEVER edit `contract.frozen.md`",
        "NEVER record `qa-record --result pass` without",
    ]
    for phrase in must_be_present:
        assert phrase in rendered, f"hard policy lost: {phrase!r}"


# ---------------------------------------------------------------------------
# Content-level sanity
# ---------------------------------------------------------------------------

def test_manifest_renders_project_name_from_brief(tmp_path: Path):
    """Brief's `# Project brief: <name>` becomes the manifest header."""
    paths = _fixture_paths(tmp_path)
    (paths.repo / ".agent" / "project_brief.md").write_text(
        "# Project brief: TestProject\n\n## Vision (one sentence)\nfoo\n"
    )
    rendered = render_manifest(paths, tier=TIER_SINGLE_REPO)
    assert "Project context — TestProject" in rendered


def test_manifest_falls_back_to_repo_dir_name(tmp_path: Path):
    """No brief, no plan, no config — falls back to the directory name."""
    paths = _fixture_paths(tmp_path)
    rendered = render_manifest(paths, tier=TIER_SINGLE_REPO)
    assert f"Project context — {tmp_path.name}" in rendered


def test_workflow_contract_substitutes_bug_prefix(tmp_path: Path):
    """When config declares `bugs.id_prefix`, that value appears in the
    rendered workflow contract (if the template uses it)."""
    paths = _fixture_paths(tmp_path)
    (paths.repo / ".agent" / "config.yaml").write_text(
        "bugs:\n  id_prefix: BE\n"
    )
    rendered = render_manifest(paths, tier=TIER_SINGLE_REPO)
    # The template doesn't currently embed bug_prefix in workflow text
    # (it points users to `.agent/config.yaml`); but if it ever does,
    # this test guards the substitution path.
    assert "<PREFIX>" not in rendered or "BE" in rendered


def test_manifest_includes_all_categorized_section_headers(tmp_path: Path):
    """Section headers from _CATEGORY_RENDER_ORDER appear when at least
    one entry uses that category."""
    paths = _fixture_paths(tmp_path)
    rendered = render_manifest(paths, tier=TIER_PROJECT_ROOT)
    # Spot-check the headers that should always be present at project-root
    expected_headers = [
        "Technical architecture",
        "Data layer",
        "Bug-fix lookups",
        "Anti-patterns",
        "Working memory",
        "Episodic memory",
        "Semantic memory",
        "Style + conventions",
    ]
    for header in expected_headers:
        assert header in rendered, f"missing section header: {header!r}"
