"""Tests for the .agent/dashboard.md generator."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from dotagent.paths import Paths
from dotagent.project.model import (
    Contract,
    Cycle,
    Module,
    ModuleState,
    Project,
    QAResult,
)
from dotagent.render.dashboard import render_dashboard


def _paths(tmp_path: Path) -> Paths:
    (tmp_path / ".agent").mkdir()
    return Paths(repo=tmp_path)


def _project(name: str = "demo", **module_kwargs) -> Project:
    return Project(name=name, modules=dict(module_kwargs))


def _iso_days_ago(n: int) -> str:
    return (
        (datetime.now(timezone.utc) - timedelta(days=n))
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )


def test_empty_project_renders_all_sections_with_zeros(tmp_path: Path):
    paths = _paths(tmp_path)
    out = render_dashboard(_project(), paths)
    assert "# Project dashboard — demo" in out
    assert "## 📜 Open contracts (0)" in out
    assert "## 🧪 Pending QA (0)" in out
    assert "## ⏰ Stalled" in out
    assert "## 📅 Doc staleness" in out
    assert "## 📡 Recent activity" in out


def test_open_contract_appears_in_dashboard(tmp_path: Path):
    paths = _paths(tmp_path)
    m = Module(
        id="01-auth", name="Auth", state=ModuleState.DEFINED,
        cycles=[Cycle(n=1, contract=Contract(status="frozen", round=2))],
    )
    project = _project(**{"01-auth": m})
    out = render_dashboard(project, paths)
    assert "Open contracts (1)" in out
    assert "`01-auth`" in out
    assert "**frozen**" in out


def test_closed_cycle_excluded_from_open_contracts(tmp_path: Path):
    paths = _paths(tmp_path)
    m = Module(
        id="01-auth", name="Auth", state=ModuleState.DEFINED,
        cycles=[
            Cycle(
                n=1,
                contract=Contract(status="frozen"),
                qa_result=QAResult(cycle=1, passed=True, rationale="ok"),
            ),
        ],
    )
    project = _project(**{"01-auth": m})
    out = render_dashboard(project, paths)
    assert "Open contracts (0)" in out


def test_pending_qa_after_handoff_no_qa_result(tmp_path: Path):
    paths = _paths(tmp_path)
    m = Module(
        id="02-billing", name="Billing", state=ModuleState.DEFINED,
        cycles=[Cycle(n=1, handoff_at=_iso_days_ago(2))],
    )
    project = _project(**{"02-billing": m})
    out = render_dashboard(project, paths)
    assert "Pending QA (1)" in out
    assert "`02-billing`" in out


def test_stalled_cycle_when_handoff_older_than_14_days(tmp_path: Path):
    paths = _paths(tmp_path)
    m = Module(
        id="03-old", name="Old", state=ModuleState.DEFINED,
        cycles=[Cycle(n=1, handoff_at=_iso_days_ago(30))],
    )
    project = _project(**{"03-old": m})
    out = render_dashboard(project, paths)
    assert "Stalled" in out
    assert "`03-old`" in out
    assert "30d ago" in out


def test_fresh_cycle_not_stalled(tmp_path: Path):
    paths = _paths(tmp_path)
    m = Module(
        id="04-fresh", name="Fresh", state=ModuleState.DEFINED,
        cycles=[Cycle(n=1, handoff_at=_iso_days_ago(3))],
    )
    project = _project(**{"04-fresh": m})
    out = render_dashboard(project, paths)
    # Should appear in Pending QA, not in Stalled
    assert "Pending QA (1)" in out
    assert "Stalled (>14d) (0)" in out


def test_doc_staleness_flags_old_files(tmp_path: Path):
    paths = _paths(tmp_path)
    (tmp_path / "docs").mkdir()
    stale = tmp_path / "docs" / "architecture.md"
    stale.write_text("# old\n")
    # Set mtime to 90 days ago
    import os
    ninety_days_ago = (datetime.now(timezone.utc) - timedelta(days=90)).timestamp()
    os.utime(stale, (ninety_days_ago, ninety_days_ago))

    out = render_dashboard(_project(), paths)
    assert "docs/architecture.md" in out
    assert "Doc staleness" in out


def test_fresh_doc_not_flagged(tmp_path: Path):
    paths = _paths(tmp_path)
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "architecture.md").write_text("# fresh\n")
    out = render_dashboard(_project(), paths)
    assert "Doc staleness (>60d) (0)" in out


def test_banner_present(tmp_path: Path):
    paths = _paths(tmp_path)
    out = render_dashboard(_project(), paths)
    assert "<!-- generated by dotagent" in out


def test_recent_activity_empty_when_no_events(tmp_path: Path):
    paths = _paths(tmp_path)
    out = render_dashboard(_project(), paths)
    assert "No events recorded yet" in out
