"""Tests for the docs/service-registry.md generator."""

from __future__ import annotations

from dotagent.git_layout import GitLayout, MetaConfig, RepoEntry
from dotagent.render.service_registry import render_service_registry


def test_empty_layout_renders_placeholder():
    layout = GitLayout(meta=MetaConfig())
    out = render_service_registry(layout)
    assert "# Service registry" in out
    assert "No services declared" in out
    assert "<!-- generated by dotagent" in out


def test_single_repo_renders_table_row():
    layout = GitLayout(
        meta=MetaConfig(),
        repos=[
            RepoEntry(
                id="aigent-portal", path="customer-portal",
                default_branch="main", role="Customer UI",
                remote="git@github.com:org/aigent-portal.git",
            ),
        ],
    )
    out = render_service_registry(layout)
    assert "aigent-portal" in out
    assert "customer-portal/" in out
    assert "Customer UI" in out
    assert "main" in out


def test_aigent_3_repo_layout():
    """The user's actual layout: 3 service repos + 1 meta."""
    layout = GitLayout(
        meta=MetaConfig(),
        repos=[
            RepoEntry(id="aigent-portal", path="customer-portal", role="Frontend"),
            RepoEntry(id="aigent-backend", path="backend", role="API + workers"),
            RepoEntry(id="aigent-admin", path="admin", role="Admin tools"),
        ],
    )
    out = render_service_registry(layout)
    for repo in ("aigent-portal", "aigent-backend", "aigent-admin"):
        assert repo in out, f"missing {repo}"


def test_role_unset_renders_placeholder():
    layout = GitLayout(
        meta=MetaConfig(),
        repos=[RepoEntry(id="foo", path="foo")],
    )
    out = render_service_registry(layout)
    assert "_(unset)_" in out  # role placeholder


def test_remote_local_falls_back_to_marker():
    layout = GitLayout(
        meta=MetaConfig(),
        repos=[RepoEntry(id="foo", path="foo", role="x")],
    )
    out = render_service_registry(layout)
    assert "_(local)_" in out


def test_banner_warns_against_hand_edit():
    layout = GitLayout(meta=MetaConfig())
    out = render_service_registry(layout)
    assert "do not hand-edit" in out
    assert "git.yaml" in out  # tells user where to edit
