"""Tests for the per-module HISTORY.md generator."""

from __future__ import annotations

from dotagent.project.model import (
    Contract,
    Cycle,
    Module,
    ModuleState,
    QAResult,
)
from dotagent.render.module_history import render_module_history


def _module(id: str = "01-auth", **overrides) -> Module:
    defaults = dict(id=id, name="Auth service", state=ModuleState.DEFINED)
    defaults.update(overrides)
    return Module(**defaults)


def test_empty_module_renders_placeholder():
    m = _module()
    out = render_module_history(m)
    assert "Module history" in out
    assert "01-auth" in out
    assert "No cycles yet" in out
    assert "<!-- generated by dotagent" in out


def test_module_with_one_in_progress_cycle():
    m = _module(cycles=[Cycle(n=1, started_at="2026-05-01T10:00:00Z")])
    out = render_module_history(m)
    assert "Cycle 01" in out
    assert "🟢 In progress" in out
    assert "2026-05-01" in out


def test_module_with_passed_qa():
    m = _module(
        cycles=[
            Cycle(
                n=1,
                started_at="2026-05-01T10:00:00Z",
                handoff_at="2026-05-02T11:00:00Z",
                qa_result=QAResult(
                    cycle=1, passed=True,
                    rationale="All acceptance criteria met. No regressions.",
                    recorded_by="codex", recorded_at="2026-05-03T09:00:00Z",
                ),
            ),
        ],
    )
    out = render_module_history(m)
    assert "✓ Passed QA" in out
    assert "All acceptance criteria met" in out
    assert "`codex`" in out


def test_module_with_failed_qa_keeps_rationale():
    m = _module(
        cycles=[
            Cycle(
                n=1,
                qa_result=QAResult(
                    cycle=1, passed=False,
                    rationale="Missing test for refresh-token rotation.",
                ),
            ),
        ],
    )
    out = render_module_history(m)
    assert "✗ Failed QA" in out
    assert "refresh-token rotation" in out


def test_cycles_render_newest_first():
    m = _module(
        cycles=[
            Cycle(n=1, started_at="2026-05-01T10:00:00Z"),
            Cycle(n=2, started_at="2026-05-10T10:00:00Z"),
            Cycle(n=3, started_at="2026-05-20T10:00:00Z"),
        ],
    )
    out = render_module_history(m)
    pos_3 = out.index("Cycle 03")
    pos_1 = out.index("Cycle 01")
    assert pos_3 < pos_1, "newest cycle (Cycle 03) must appear before oldest"


def test_cross_module_slice_marker():
    m = _module(cross_module="auth-shared")
    out = render_module_history(m)
    assert "Cross-module slice of" in out
    assert "auth-shared" in out


def test_blocked_state_surfaced():
    m = _module(state=ModuleState.DEFINED, blocked_reason="Waiting on upstream contract")
    out = render_module_history(m)
    assert "Blocked" in out
    assert "upstream contract" in out


def test_implements_features_listed():
    m = _module(implements_features=["FEAT-01", "FEAT-07"])
    out = render_module_history(m)
    assert "FEAT-01" in out
    assert "FEAT-07" in out


def test_contract_negotiation_status():
    m = _module(
        cycles=[
            Cycle(
                n=1,
                contract=Contract(round=2, rounds_max=3, status="proposed"),
            ),
        ],
    )
    out = render_module_history(m)
    assert "Contract negotiation (round 2/3)" in out


def test_files_changed_count_with_truncation():
    m = _module(
        cycles=[
            Cycle(
                n=1,
                files_changed=[f"src/file{i}.py" for i in range(12)],
            ),
        ],
    )
    out = render_module_history(m)
    assert "Files changed (12)" in out
    assert "+7 more" in out  # 12 - 5 preview
