"""Backup + restore for AI-tool config files dotagent overwrites.

When `dotagent init` or `dotagent sync` is about to write CLAUDE.md /
.cursorrules / .github/copilot-instructions.md / AGENTS.md and a non-empty
file already exists at that path that wasn't generated by dotagent, we copy
the original to `.agent/.imported/<basename>.original` before overwriting.

Backups are written exactly once — subsequent `sync` runs won't clobber an
earlier backup. `dotagent restore-original` copies them back if you decide
you don't want dotagent managing one of these files.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from .paths import Paths


_DOTAGENT_MARKER = "generated by dotagent"


# Mapping: friendly name → relative path inside the repo.
MANAGED_FILES: dict[str, str] = {
    "claude": "CLAUDE.md",
    "cursor": ".cursorrules",
    "copilot": ".github/copilot-instructions.md",
    "opencode": "AGENTS.md",
}


@dataclass
class BackupResult:
    name: str
    source: Path
    backup: Path
    skipped_reason: str = ""

    @property
    def ok(self) -> bool:
        return not self.skipped_reason


def _is_dotagent_managed(path: Path) -> bool:
    try:
        head = path.read_text(errors="replace")[:400]
    except OSError:
        return False
    return _DOTAGENT_MARKER in head


def backup_existing(paths: Paths) -> list[BackupResult]:
    """Back up any pre-existing AI-tool configs that aren't already dotagent-managed."""
    results: list[BackupResult] = []
    paths.imported.mkdir(parents=True, exist_ok=True)
    for name, rel in MANAGED_FILES.items():
        src = paths.repo / rel
        if not src.exists() or not src.is_file():
            continue
        target = paths.imported / f"{Path(rel).name}.original"
        if target.exists():
            results.append(BackupResult(name=name, source=src, backup=target,
                                        skipped_reason="backup already exists"))
            continue
        if _is_dotagent_managed(src):
            results.append(BackupResult(name=name, source=src, backup=target,
                                        skipped_reason="already a dotagent-managed file"))
            continue
        shutil.copy2(src, target)
        results.append(BackupResult(name=name, source=src, backup=target))
    return results


def list_backups(paths: Paths) -> list[Path]:
    if not paths.imported.exists():
        return []
    return sorted(paths.imported.glob("*.original"))


def restore_one(paths: Paths, name: str) -> Path:
    if name not in MANAGED_FILES:
        raise KeyError(f"unknown managed file: {name}. Known: {sorted(MANAGED_FILES)}")
    rel = MANAGED_FILES[name]
    src = paths.imported / f"{Path(rel).name}.original"
    if not src.exists():
        raise FileNotFoundError(
            f"No backup at {src}. dotagent only backs up the *first* time it overwrites."
        )
    target = paths.repo / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, target)
    return target


def restore_all(paths: Paths) -> list[Path]:
    restored: list[Path] = []
    for name in MANAGED_FILES:
        try:
            restored.append(restore_one(paths, name))
        except FileNotFoundError:
            continue
    return restored
