"""Ingest existing AI-tool configs (CLAUDE.md, .cursorrules, copilot-instructions, AGENTS.md)
into seeds for `.agent/{style,rules,architecture,patterns,preferences}.md`.

Heuristics:
- H2 sections matching keywords (style, rules, architecture, patterns, preferences) are
  routed into the matching `.agent/*.md` file.
- Sections that don't match a keyword are appended into `architecture.md` under a
  "Legacy notes" sub-heading, so nothing is lost.
- The dotagent header marker is stripped to avoid feedback loops on re-render.

This runs before scaffold so we don't overwrite an ingested file with a blank scaffold.
"""

from __future__ import annotations

import re
from pathlib import Path

_HEADER_MARKERS = (
    "<!-- generated by dotagent",
    "# .cursorrules — generated by dotagent",
    "# Project context for Claude Code",
    "# Project context for",
    "# Copilot project instructions",
    "# AGENTS.md",
)

_KEYWORDS = {
    "style": ["style", "coding style"],
    "rules": ["rule", "rules", "constraint", "constraints", "do not", "must"],
    "architecture": ["architecture", "system", "components", "services"],
    "patterns": ["pattern", "patterns", "convention", "conventions"],
    "preferences": ["preference", "preferences", "personal"],
}

_H2 = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


def _strip_dotagent_header(text: str) -> str:
    out_lines: list[str] = []
    for line in text.splitlines():
        ls = line.strip()
        if any(ls.startswith(m) for m in _HEADER_MARKERS):
            continue
        out_lines.append(line)
    return "\n".join(out_lines).strip()


def _split_h2(text: str) -> list[tuple[str, str]]:
    parts: list[tuple[str, str]] = []
    matches = list(_H2.finditer(text))
    if not matches:
        return [("Document", text.strip())] if text.strip() else []
    for i, m in enumerate(matches):
        title = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        parts.append((title, text[start:end].strip()))
    return parts


def _route(title: str) -> str | None:
    lt = title.lower()
    for key, words in _KEYWORDS.items():
        if any(w in lt for w in words):
            return key
    return None


def ingest_existing(repo: Path) -> dict[str, str]:
    """Read every existing AI-tool config and merge into bucketed source files.

    Returns dict mapping section key (`style|rules|architecture|patterns|preferences`)
    → markdown body. Empty buckets are omitted.
    """
    candidates = [
        repo / "CLAUDE.md",
        repo / ".cursorrules",
        repo / ".github" / "copilot-instructions.md",
        repo / "AGENTS.md",
    ]
    buckets: dict[str, list[str]] = {k: [] for k in _KEYWORDS}
    leftovers: list[str] = []
    for path in candidates:
        if not path.exists() or not path.is_file():
            continue
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        text = _strip_dotagent_header(text)
        if not text:
            continue
        for title, body in _split_h2(text):
            key = _route(title)
            block = f"### From `{path.relative_to(repo)}` — {title}\n\n{body}".rstrip()
            if key:
                buckets[key].append(block)
            else:
                leftovers.append(block)

    out: dict[str, str] = {}
    for key, blocks in buckets.items():
        if blocks:
            out[key] = "\n\n".join(blocks).strip() + "\n"
    if leftovers:
        existing_arch = out.get("architecture", "").rstrip()
        legacy = "\n\n## Legacy notes (auto-imported, please curate)\n\n" + "\n\n".join(leftovers).strip() + "\n"
        out["architecture"] = (existing_arch + legacy).strip() + "\n" if existing_arch else legacy.strip() + "\n"
    return out
