"""End-to-end regression test mirroring the Aigent project audit scenario.

User audit (2026-05-20) revealed several real gaps when running against a
real layered-tier project:

1. Brief parser couldn't read `**OBJ-01 · Title**:` shape (fixed in 0.4.4)
2. plan.yaml missing top-level name/goal/success_criteria → empty dashboard titles
3. SCOPE.md regenerate would HOLLOW the file because render_scope() reads
   the missing fields without fallback
4. traceability.audit_feat_to_module read only module.yaml::implements_features,
   ignoring plan.yaml::features_to_modules
5. Frozen contracts missing FEAT-NN treated as fail (should be info — frozen
   = immutable, can't be edited)
6. No regenerate command — user had to find an unrelated state-changing op
   to trigger SCOPE.md regen

This test asserts all six are fixed and stay fixed.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from dotagent.config import merge_defaults
from dotagent.paths import Paths
from dotagent.project.brief import Brief, Feature, Objective, parse, write_stub
from dotagent.project.handoff import render_scope
from dotagent.project.model import (
    Contract,
    ContractStatus,
    Cycle,
    Module,
    Project,
    save_module,
    save_project,
    load_project,
)
from dotagent.project.traceability import (
    ContractRef,
    audit_feat_to_module,
    audit_module_to_contract,
)
from dotagent.scaffold import scaffold_agent_dir
from dotagent.util import dump_yaml


# ---------------------------------------------------------------------------
# Aigent-shape brief (the actual format the user has)
# ---------------------------------------------------------------------------

_AIGENT_BRIEF = """# Project brief: Aigent

**Last reviewed:** 2026-05-01  ·  **Brief version:** 2  ·  **Owner:** alice  ·  **Stage:** beta

## Vision (one sentence)
Universal AI chat layer that gets out of users' way.

## Business objectives
- **OBJ-01 · Universal AI chat layer**: 100 paying customers in 90 days
- **OBJ-02 · Cross-tenant isolation**: zero security incidents year one

## Features

### FEAT-01 · Multi-LLM routing
**Serves:** OBJ-01
**Expected outcome:** route prompts to cheapest provider that meets latency
**What it must do:**
- detect available models per tenant
- route by cost + latency budget

### FEAT-02 · Tenant boundary enforcement
**Serves:** OBJ-02
**Expected outcome:** zero cross-tenant data exposure
**What it must do:**
- every query filters by tenant_id

## Hard rules
- **RULE-01 · Tenant isolation** — _why: BUG-014 leak; how: filter every query_
"""


# ---------------------------------------------------------------------------
# Fix 1: parser reads the Aigent-shape brief end-to-end
# ---------------------------------------------------------------------------

def test_aigent_brief_parses_objectives_and_features():
    """The audit-report shape parses cleanly."""
    brief = parse(_AIGENT_BRIEF)
    assert brief.name == "Aigent"
    assert brief.brief_version == 2
    assert len(brief.objectives) == 2
    assert brief.objective_ids == ["OBJ-01", "OBJ-02"]
    assert "Universal AI chat layer" in brief.objectives[0].text
    assert "100 paying customers" in brief.objectives[0].text

    assert len(brief.features) == 2
    assert brief.feature_ids == ["FEAT-01", "FEAT-02"]
    assert brief.features[0].serves == ["OBJ-01"]

    assert len(brief.hard_rules) == 1
    assert brief.hard_rules[0].id == "RULE-01"


# ---------------------------------------------------------------------------
# Fix 3: render_scope() falls back to brief when plan.yaml missing fields
# ---------------------------------------------------------------------------

def test_render_scope_falls_back_to_brief_when_plan_is_thin():
    """A plan.yaml missing name/goal/description/etc. should NOT produce
    an empty SCOPE.md. Brief data fills the gaps."""
    project = Project(name="")  # the layered-tier shape: empty top-level
    brief = parse(_AIGENT_BRIEF)
    scope = render_scope(project, brief=brief)
    # name falls back to brief.name
    assert "Aigent" in scope
    # goal falls back to brief.vision
    assert "Universal AI chat layer" in scope
    # banner present
    assert "generated by dotagent" in scope.lower()


def test_render_scope_works_without_brief_too():
    """If no brief is available, render_scope() still emits a usable file
    with explicit '(unset — add X)' markers — does NOT crash."""
    project = Project(name="")
    scope = render_scope(project, brief=None)
    assert "(unset" in scope
    assert "generated by dotagent" in scope.lower()


# ---------------------------------------------------------------------------
# Fix 4: audit_feat_to_module reads BOTH sources
# ---------------------------------------------------------------------------

def test_audit_reads_plan_features_to_modules():
    """When module.yaml lacks implements_features but plan.yaml has
    features_to_modules, the audit should accept the latter as evidence."""
    brief = Brief(features=[
        Feature(id="FEAT-01", name="a", serves=["OBJ-01"]),
        Feature(id="FEAT-02", name="b", serves=["OBJ-01"]),
    ])
    project = Project(
        name="x",
        brief_features_covered=["FEAT-01", "FEAT-02"],
        features_to_modules={
            "FEAT-01": ["M01"],
            "FEAT-02": ["M02"],
        },
    )
    # Modules don't have implements_features set
    modules = [
        Module(id="M01", name="auth"),
        Module(id="M02", name="billing"),
    ]

    findings = audit_feat_to_module(brief, project, modules)
    # Both FEATs covered via plan.yaml — no findings
    assert findings == []


def test_audit_reads_module_implements_features_too():
    """Backward compat: when modules carry implements_features, that
    works as before."""
    brief = Brief(features=[Feature(id="FEAT-01", name="a", serves=["OBJ-01"])])
    project = Project(name="x", brief_features_covered=["FEAT-01"])
    modules = [Module(id="M01", name="a", implements_features=["FEAT-01"])]
    findings = audit_feat_to_module(brief, project, modules)
    assert findings == []


def test_audit_unions_both_sources():
    """Mixed shape: some FEATs in modules, others in plan."""
    brief = Brief(features=[
        Feature(id="FEAT-A", name="a", serves=["OBJ-1"]),
        Feature(id="FEAT-B", name="b", serves=["OBJ-1"]),
    ])
    project = Project(
        name="x",
        brief_features_covered=["FEAT-A", "FEAT-B"],
        features_to_modules={"FEAT-B": ["M-only-in-plan"]},
    )
    modules = [
        Module(id="M-only-in-module", name="a", implements_features=["FEAT-A"]),
        Module(id="M-only-in-plan", name="b"),
    ]
    findings = audit_feat_to_module(brief, project, modules)
    assert findings == []


def test_audit_flags_when_neither_source_covers():
    """If a FEAT is in brief_features_covered but neither source has it,
    that's still a finding."""
    brief = Brief(features=[Feature(id="FEAT-X", name="x", serves=["OBJ-1"])])
    project = Project(name="x", brief_features_covered=["FEAT-X"])
    modules = []
    findings = audit_feat_to_module(brief, project, modules)
    assert len(findings) == 1
    assert "FEAT-X" in findings[0].message


# ---------------------------------------------------------------------------
# Fix 5: frozen contracts missing FEAT are info, not fail
# ---------------------------------------------------------------------------

def test_active_contract_without_feat_is_still_fail():
    """A LIVE contract missing FEAT must still fail — the rule is alive."""
    modules = [Module(id="M01", name="a", implements_features=["FEAT-01"])]
    contracts = [ContractRef(
        module_id="M01", cycle_n=1, is_frozen=False,
        body=(
            "<!-- anchor: business-traceability -->\n(empty)\n"
            "<!-- anchor: negotiation-log -->\n"
        ),
    )]
    findings = audit_module_to_contract(modules, contracts)
    assert len(findings) == 1
    assert findings[0].severity == "fail"


def test_frozen_contract_without_feat_is_info_not_fail():
    """Frozen = immutable. Demanding edits is wrong. Info, not fail."""
    modules = [Module(id="M01", name="a")]
    contracts = [ContractRef(
        module_id="M01", cycle_n=1, is_frozen=True,
        body=(
            "<!-- anchor: business-traceability -->\n(empty — pre-schema)\n"
            "<!-- anchor: negotiation-log -->\n"
        ),
    )]
    findings = audit_module_to_contract(modules, contracts)
    assert len(findings) == 1
    assert findings[0].severity == "info"
    assert findings[0].code == "frozen-contract-no-feat"


# ---------------------------------------------------------------------------
# Fix 2/3: full layered-tier scenario — plan.yaml thin + brief populated
# ---------------------------------------------------------------------------

def test_full_aigent_scenario_end_to_end(tmp_path: Path):
    """End-to-end mirroring the user's exact failure mode:

    - plan.yaml has no top-level name/goal/description
    - plan.yaml has features_to_modules (layered-tier shape)
    - brief uses **OBJ-01 · Title**: shape
    - module.yaml files have NO implements_features

    After 0.4.5 all three audits should be either clean or info-only.
    """
    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    dump_yaml(paths.config, merge_defaults({"project": {"name": "Aigent"}}))
    (tmp_path / ".agent" / "project_brief.md").write_text(_AIGENT_BRIEF)

    # plan.yaml in layered-tier shape: no name/goal/etc, has features_to_modules
    dump_yaml(paths.project_plan, {
        "brief_version": 2,
        "brief_features_covered": ["FEAT-01", "FEAT-02"],
        "features_to_modules": {"FEAT-01": ["M01"], "FEAT-02": ["M02"]},
        "modules": {
            "M01": {"state": "planned"},
            "M02": {"state": "in_progress"},
        },
        "repos": [
            {"id": "backend", "path": "./backend",
             "remote": "git@x:y.git", "default_branch": "main", "role": "api"},
        ],
    })

    project = load_project(paths)
    brief = parse(_AIGENT_BRIEF)
    modules = list(project.modules.values())

    # 1. Brief parses with all IDs
    assert brief.objective_ids == ["OBJ-01", "OBJ-02"]
    assert brief.feature_ids == ["FEAT-01", "FEAT-02"]

    # 2. SCOPE.md regenerates with brief fallback (not hollow)
    scope = render_scope(project, brief=brief)
    assert "Aigent" in scope                       # name from brief
    assert "Universal AI chat layer" in scope      # goal from brief.vision
    assert "(unset" not in scope.split("##")[0]    # title isn't unset

    # 3. FEAT→Module audit passes via plan.yaml::features_to_modules
    findings = audit_feat_to_module(brief, project, modules)
    feat_findings = [f for f in findings if f.code == "feat-no-module"]
    assert feat_findings == [], (
        "After 0.4.5, FEATs covered by features_to_modules shouldn't "
        f"be flagged as unmapped. Got: {feat_findings}"
    )


# ---------------------------------------------------------------------------
# Fix 6: regenerate command exists + safe + non-destructive
# ---------------------------------------------------------------------------

def test_regenerate_command_writes_scope_with_brief_fallback(tmp_path: Path):
    """Test the actual CLI command works on a thin plan.yaml + populated brief.

    This is the failure case the user hit: 'dotagent sync' didn't regenerate
    SCOPE.md, and there was no other command to trigger it without changing
    state. The new `dotagent project regenerate` fills that gap.
    """
    import os
    from click.testing import CliRunner
    from dotagent.cli import main

    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    dump_yaml(paths.config, merge_defaults({"project": {"name": "Aigent"}}))
    (tmp_path / ".agent" / ".version").write_text("0.4.0\n")
    (tmp_path / ".agent" / "project_brief.md").write_text(_AIGENT_BRIEF)
    dump_yaml(paths.project_plan, {
        "brief_features_covered": ["FEAT-01"],
        "features_to_modules": {"FEAT-01": ["M01"]},
        "modules": {"M01": {"state": "planned"}},
        "repos": [],
    })

    runner = CliRunner()
    orig = os.getcwd()
    os.chdir(tmp_path)
    try:
        result = runner.invoke(main, ["project", "regenerate"], catch_exceptions=False)
    finally:
        os.chdir(orig)

    assert result.exit_code == 0, result.output
    assert paths.project_scope_md.exists()
    body = paths.project_scope_md.read_text()
    # Banner present (fixes the SCOPE.md "missing banner" warning)
    assert "generated by dotagent" in body.lower()
    # Content NOT hollow — brief fallback worked
    assert "Aigent" in body
    assert "Universal AI chat layer" in body


def test_regenerate_dry_run_writes_nothing(tmp_path: Path):
    """--dry-run reports without touching the filesystem."""
    import os
    from click.testing import CliRunner
    from dotagent.cli import main

    paths = Paths(repo=tmp_path)
    scaffold_agent_dir(paths)
    dump_yaml(paths.config, merge_defaults({"project": {"name": "x"}}))
    (tmp_path / ".agent" / ".version").write_text("0.4.0\n")
    dump_yaml(paths.project_plan, {"modules": {"M01": {"state": "planned"}}})

    # Capture pre-state
    scope_existed = paths.project_scope_md.exists()

    runner = CliRunner()
    orig = os.getcwd()
    os.chdir(tmp_path)
    try:
        result = runner.invoke(main, ["project", "regenerate", "--dry-run"],
                               catch_exceptions=False)
    finally:
        os.chdir(orig)

    assert result.exit_code == 0
    assert "[--dry-run]" in result.output
    # File state unchanged
    assert paths.project_scope_md.exists() == scope_existed
