"""`.agent/dashboard.md` — project health snapshot.

Single-page answer to "what's the state of my project right now?":

- Open contracts (across all modules)
- Pending QA (dev-handoff received but no QA result yet)
- Stalled cycles (>14 days since last activity)
- Doc staleness (canonical docs/*.md older than referenced code)
- Recent activity (top N events from episodic memory)

Pure summary view — owns no state; all data comes from existing
sources (Project, EpisodicMemory, file mtimes). Re-renders on every
`dotagent sync` and `dotagent project regenerate`.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from ..paths import Paths
from ..project.model import Project


_BANNER = (
    "<!-- generated by dotagent · project dashboard · do not hand-edit "
    "(this is a derived view of project state) -->"
)

_STALLED_DAYS = 14
_RECENT_EVENT_LIMIT = 10
_DOC_STALENESS_DAYS = 60
_CANONICAL_DOCS = (
    "docs/architecture.md",
    "docs/bug-registry.md",
    "docs/anti-patterns.md",
    "docs/redis-keys.md",
    "docs/db-impact-map.md",
    "docs/dependency-map.md",
)


def render_dashboard(project: Project, paths: Paths) -> str:
    """Render the dashboard for a loaded project."""
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat(timespec="seconds").replace("+00:00", "Z")

    open_contracts = _collect_open_contracts(project)
    pending_qa = _collect_pending_qa(project)
    stalled = _collect_stalled_cycles(project, now)
    doc_staleness = _collect_doc_staleness(paths, now)
    recent_events = _collect_recent_events(paths)

    parts: list[str] = [
        _BANNER,
        f"<!-- rendered-at: {now_iso} · project: {project.name or '(unset)'} -->",
        "",
        f"# Project dashboard — {project.name or '(unset)'}",
        "",
        f"_Snapshot rendered {now_iso}. Re-run `dotagent sync` to refresh._",
        "",
    ]

    parts.append(_section_open_contracts(open_contracts))
    parts.append(_section_pending_qa(pending_qa))
    parts.append(_section_stalled(stalled))
    parts.append(_section_doc_staleness(doc_staleness))
    parts.append(_section_recent_activity(recent_events))

    return "\n\n".join(p for p in parts if p).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def _section_open_contracts(items: list[tuple[str, int, str]]) -> str:
    lines = [f"## 📜 Open contracts ({len(items)})", ""]
    if not items:
        lines.append("_None. Every module's current cycle is either pre-contract or QA-pass._")
        return "\n".join(lines)
    for module_id, cycle_n, status in items:
        lines.append(f"- `{module_id}` · cycle {cycle_n:02d} · **{status}**")
    return "\n".join(lines)


def _section_pending_qa(items: list[tuple[str, int, str]]) -> str:
    lines = [f"## 🧪 Pending QA ({len(items)})", ""]
    if not items:
        lines.append("_No cycles awaiting QA review._")
        return "\n".join(lines)
    for module_id, cycle_n, handoff_at in items:
        lines.append(
            f"- `{module_id}` · cycle {cycle_n:02d} · dev handoff at `{handoff_at or '?'}`"
        )
    return "\n".join(lines)


def _section_stalled(items: list[tuple[str, int, int]]) -> str:
    lines = [f"## ⏰ Stalled (>{_STALLED_DAYS}d) ({len(items)})", ""]
    if not items:
        lines.append("_Nothing stalled._")
        return "\n".join(lines)
    for module_id, cycle_n, age_days in items:
        lines.append(f"- `{module_id}` · cycle {cycle_n:02d} · last activity {age_days}d ago")
    return "\n".join(lines)


def _section_doc_staleness(items: list[tuple[str, int]]) -> str:
    lines = [f"## 📅 Doc staleness (>{_DOC_STALENESS_DAYS}d) ({len(items)})", ""]
    if not items:
        lines.append("_All canonical docs have been touched recently._")
        return "\n".join(lines)
    for rel, age_days in items:
        lines.append(f"- `{rel}` — {age_days}d since last edit")
    return "\n".join(lines)


def _section_recent_activity(events: list[dict]) -> str:
    lines = [f"## 📡 Recent activity (last {_RECENT_EVENT_LIMIT})", ""]
    if not events:
        lines.append("_No events recorded yet (`.agent/memory/episodic/` empty)._")
        return "\n".join(lines)
    for ev in events:
        ts = ev.get("ts", "?")
        actor = ev.get("actor", "?")
        tool = ev.get("tool", "?")
        kind = ev.get("kind", "?")
        summary = (ev.get("summary") or "").strip().splitlines()[0] if ev.get("summary") else ""
        line = f"- `{ts}` · `{actor}` via `{tool}` · {kind}"
        if summary:
            line += f" — {summary}"
        lines.append(line)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Data collectors
# ---------------------------------------------------------------------------

def _collect_open_contracts(project: Project) -> list[tuple[str, int, str]]:
    """(module_id, cycle_n, status) for every module whose current cycle
    has a non-frozen contract OR a frozen contract awaiting handoff/QA."""
    out: list[tuple[str, int, str]] = []
    for module in project.modules.values():
        cycle = module.current_cycle
        if cycle is None or cycle.contract is None:
            continue
        status = cycle.contract.status
        # Closed cycles (qa_result.passed) aren't "open"
        if cycle.qa_result is not None and cycle.qa_result.passed:
            continue
        out.append((module.id, cycle.n, status))
    return out


def _collect_pending_qa(project: Project) -> list[tuple[str, int, str]]:
    """Cycles where dev-handoff was made but QA hasn't recorded yet."""
    out: list[tuple[str, int, str]] = []
    for module in project.modules.values():
        cycle = module.current_cycle
        if cycle is None or not cycle.handoff_at:
            continue
        if cycle.qa_result is not None:
            continue
        out.append((module.id, cycle.n, cycle.handoff_at))
    return out


def _collect_stalled_cycles(
    project: Project, now: datetime
) -> list[tuple[str, int, int]]:
    """Active cycles whose latest activity timestamp is > _STALLED_DAYS ago."""
    out: list[tuple[str, int, int]] = []
    threshold = now - timedelta(days=_STALLED_DAYS)
    for module in project.modules.values():
        cycle = module.current_cycle
        if cycle is None:
            continue
        # Skip cleanly-closed cycles
        if cycle.qa_result is not None and cycle.qa_result.passed:
            continue
        last_ts_str = cycle.handoff_at or cycle.started_at
        if not last_ts_str:
            continue
        try:
            last_ts = _parse_iso(last_ts_str)
        except ValueError:
            continue
        if last_ts < threshold:
            age_days = (now - last_ts).days
            out.append((module.id, cycle.n, age_days))
    return out


def _collect_doc_staleness(paths: Paths, now: datetime) -> list[tuple[str, int]]:
    """Canonical docs/ files whose mtime is older than _DOC_STALENESS_DAYS."""
    out: list[tuple[str, int]] = []
    threshold = now - timedelta(days=_DOC_STALENESS_DAYS)
    for rel in _CANONICAL_DOCS:
        path = paths.repo / rel
        if not path.exists():
            continue
        mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        if mtime < threshold:
            out.append((rel, (now - mtime).days))
    return out


def _collect_recent_events(paths: Paths) -> list[dict]:
    """Read the last N events from episodic memory. Best-effort — empty
    list on any failure."""
    try:
        from ..memory import EpisodicMemory
        mem = EpisodicMemory(paths)
        events = list(mem.iter_events())
    except Exception:  # noqa: BLE001
        return []
    # iter_events yields oldest-first; reverse and trim.
    events.reverse()
    return events[:_RECENT_EVENT_LIMIT]


def _parse_iso(ts: str) -> datetime:
    """Parse an ISO-8601 timestamp, tolerating trailing `Z`."""
    if ts.endswith("Z"):
        ts = ts[:-1] + "+00:00"
    dt = datetime.fromisoformat(ts)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


__all__ = ("render_dashboard",)
