"""Per-module HISTORY.md generator.

For each module in the project, writes
`.agent/project/modules/<id>/HISTORY.md` summarizing every cycle:
when it started, when contract was frozen, the QA outcome, files
changed, and the completion sha.

Answers the question "what's the history of this module?" — which
nobody could answer without manually walking the cycle directories.

Sourced from the in-memory `Module` object (parsed from module.yaml +
cycle artifacts on disk). Pure data → string transformation.
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..project.model import Cycle, Module


_BANNER = (
    "<!-- generated by dotagent · module history · do not hand-edit "
    "(edit module.yaml or cycle artifacts instead) -->"
)


def render_module_history(module: Module) -> str:
    """Render `.agent/project/modules/<id>/HISTORY.md` for one module.

    Lists cycles in reverse chronological order (newest first) so the
    most-relevant entry is at the top.
    """
    now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    lines = [
        _BANNER,
        f"<!-- rendered-at: {now_iso} · module: {module.id} · "
        f"cycles: {len(module.cycles)} -->",
        "",
        f"# Module history — `{module.id}`",
        "",
        f"- **Module name:** {module.name or '_(unset)_'}",
        f"- **State:** `{module.state}`",
    ]
    if module.implements_features:
        lines.append(f"- **Implements features:** {', '.join(module.implements_features)}")
    if module.cross_module:
        lines.append(
            f"- **Cross-module slice of:** `{module.cross_module}` "
            "(coordinate via the parent's cycle contract)"
        )
    if module.blocked_reason:
        lines.append(f"- **Blocked:** {module.blocked_reason}")
    lines.append("")

    if not module.cycles:
        lines.extend([
            "_No cycles yet for this module._",
            "",
            "Run `dotagent project cycle start` to begin the first cycle.",
            "",
        ])
        return "\n".join(lines).rstrip() + "\n"

    lines.append("## Cycles")
    lines.append("")

    for cycle in reversed(module.cycles):
        lines.extend(_render_cycle_block(cycle))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_cycle_block(cycle: Cycle) -> list[str]:
    """One H3 block per cycle. Newest first when assembled by caller."""
    out: list[str] = [f"### Cycle {cycle.n:02d}"]

    # Status badge — pass / fail / pending / not yet QA'd
    status = _cycle_status_label(cycle)
    out.append("")
    out.append(f"**Status:** {status}")
    out.append("")

    if cycle.started_at:
        out.append(f"- Started: `{cycle.started_at}`" + (
            f" (sha `{cycle.start_sha[:7]}`)" if cycle.start_sha else ""
        ))
    if cycle.handoff_at:
        out.append(f"- Dev handoff: `{cycle.handoff_at}`" + (
            f" (sha `{cycle.handoff_sha[:7]}`)" if cycle.handoff_sha else ""
        ))

    if cycle.contract:
        c = cycle.contract
        out.append(f"- Contract: `{c.status}` · round {c.round}/{c.rounds_max}")
        if c.frozen_at:
            out.append(
                f"  · frozen at `{c.frozen_at}`"
                + (f" by `{c.frozen_by}`" if c.frozen_by else "")
            )

    if cycle.qa_result:
        q = cycle.qa_result
        result = "pass ✓" if q.passed else "fail ✗"
        out.append(f"- QA: **{result}**" + (
            f" — recorded by `{q.recorded_by}` at `{q.recorded_at}`"
            if q.recorded_by else ""
        ))
        if q.rationale:
            out.append(f"  > {q.rationale.strip()}")

    if cycle.files_changed:
        # Show count + first N for context; full list lives on disk.
        n = len(cycle.files_changed)
        preview = ", ".join(f"`{p}`" for p in cycle.files_changed[:5])
        suffix = f" _(+{n - 5} more)_" if n > 5 else ""
        out.append(f"- Files changed ({n}): {preview}{suffix}")

    return out


def _cycle_status_label(cycle: Cycle) -> str:
    """Human-friendly status badge for one cycle."""
    if cycle.qa_result is not None:
        return "✓ Passed QA" if cycle.qa_result.passed else "✗ Failed QA"
    if cycle.contract and cycle.contract.frozen_at:
        return "⏳ Contract frozen — implementation / QA pending"
    if cycle.handoff_at:
        return "⏳ Dev handoff — awaiting QA"
    if cycle.contract:
        return f"📝 Contract negotiation (round {cycle.contract.round}/{cycle.contract.rounds_max})"
    return "🟢 In progress"


__all__ = ("render_module_history",)
