"""docs/service-registry.md generator (project-root tier).

The service registry is a one-page table of every service in the project:
its repo id, path, default branch, role, and remote. Derived entirely
from `.agent/git.yaml`'s `repos:` block — no human authorship needed.

Pre-0.4.10 this was a content file the user wrote by hand; now it's a
generated file kept in sync with `git.yaml`.

For service-repo CLAUDE.md, this is the INHERITED entry point for
"navigate to a sibling service."
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..git_layout import GitLayout


_BANNER = (
    "<!-- generated by dotagent · service registry · "
    "do not hand-edit (edit .agent/git.yaml instead) -->"
)


def render_service_registry(layout: GitLayout) -> str:
    """Render `docs/service-registry.md` from the parsed git.yaml.

    Empty or single-repo layouts still render a header + explanatory
    line so the file is never empty and never lies about topology.
    """
    now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    lines = [
        _BANNER,
        f"<!-- rendered-at: {now_iso} · repo count: {len(layout.repos)} -->",
        "",
        "# Service registry",
        "",
        (
            "This project's services, derived from `.agent/git.yaml`. "
            "Edit the YAML to add or rename — this file regenerates."
        ),
        "",
    ]

    if not layout.repos:
        lines.extend([
            "_No services declared in `.agent/git.yaml` yet._",
            "",
            "Add entries to the `repos:` block of `.agent/git.yaml` and run "
            "`dotagent sync` to populate this registry.",
            "",
        ])
        return "\n".join(lines).rstrip() + "\n"

    lines.append("| Service | Path | Default branch | Role | Remote |")
    lines.append("|---|---|---|---|---|")
    for repo in layout.repos:
        lines.append(
            f"| `{repo.id}` "
            f"| `{repo.path}/` "
            f"| `{repo.default_branch or '—'}` "
            f"| {repo.role or '_(unset)_'} "
            f"| {repo.remote or '_(local)_'} |"
        )
    lines.append("")
    lines.append(
        "## How to navigate"
    )
    lines.append("")
    lines.append(
        "- Each service's path is **relative to the project root**. "
        "From a service-repo CLAUDE.md, services are siblings of `..`."
    )
    lines.append(
        "- Branch policy lives in `.agent/git.yaml` under `branch_rules:`; "
        "the human dashboard is `.agent/git.md`."
    )
    lines.append(
        "- Cross-service module slices: look for `cross_module:` in any "
        "service's `.agent/project/modules/<id>/module.yaml`."
    )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


__all__ = ("render_service_registry",)
